### PR TITLE
fixed-new-ui

### PR DESCRIPTION
**Pull request by Ashutoshpadhi629**
### PR Fixes:
- Added Missing Footer in Landing Page
- Better padding and small BUGs
- Updated CourseCard and VideoCard similar to Figma file
- Responsive Sidebar and CourseList Bar

Resolves #888 

### Live Preview Link : [cms](https://cms-ashutosh-padhis-projects.vercel.app/)
{username : testuser@example.com , password : 123456}

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by Ashutoshpadhi629** [comment]
https://github.com/user-attachments/assets/0006493a-0658-4fa5-bbff-b592f7ca4f9c



https://github.com/user-attachments/assets/351c5253-b659-424a-ae28-1ca5801202c8

**Comment by Ashutoshpadhi629** [comment]
WhatsApp Image 2024-08-22 at 4 24 24 AM (1)
WhatsApp Image 2024-08-22 at 4 24 24 AM

**Comment by Ashutoshpadhi629** [comment]
hey @hkirat @siinghd , can you Review This Please. Implemented Most of the Features from figma file , tried my best to be pixel perfect . fixed the merge conflicts from #963 .

**Comment by siinghd** [comment]
@Ashutoshpadhi629 lots of conflicts sir

**Comment by Ashutoshpadhi629** [comment]
> @Ashutoshpadhi629 lots of conflicts sir

Fixed merge Conflicts @siinghd . Thank you

**Comment by Ashutoshpadhi629** [comment]
@jassBawa I just saw it , Videos and other contents are not overflowing , only the notion doc  is overflowing , will fix it. Thank you

**Pull request closed without merging**
