### PR TITLE
closes #212

### LINKED ISSUE #212: Red Squiggle Line in courses / [...courseId] / page.tsx

### PR DESCRIPTION
**Pull request by krishhh16**
closes #212

### CODE REVIEW

**Comment by krishhh16** [comment]
@hkirat had to create a new PR due to computer issues. 
Is this implementation right? Or should I create the interface in a different file?

**Comment by aryanprince** [comment]
#241 seems to be a duplicate of this issue. 

@krishhh16 I would recommend you close one of these PRs to not come across as spammy.

**Comment by krishhh16** [comment]
Ahh alright, I had to create another one because of a Linting and formatting on PR check was failing, just wanted to see if creating another one that fixes the linting problem fixes the check

**Comment by aryanprince** [comment]
@krishhh16 No worries. Feel free to ignore the failing CI PR check for now as it's being resolved in #244 for now. Your changes should still be valid!

**Pull request merged**
