### PR TITLE
Feature: New UI for Q&A section

### LINKED ISSUE #1046: The Question Page UI is broken.
The UI of the Questions and Answers Page is broken. It's totally unreadable.

### Questions List
Old Question 1

### Question Page
Old Question 2

### Answers
Old Answers 3

I have already worked on this and will make a PR soon.

### PR DESCRIPTION
**Pull request by palveVaishnav**
### PR Fixes:
- Look and feel of the questions section
- Responsive design 

Resolves #1046 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

Note :
- I have changed the redirect route after delete from /questions to /question.

### CODE REVIEW

**Comment by palveVaishnav** [comment]
https://github.com/user-attachments/assets/8f37a37f-4d1d-4ff8-9a9f-51726594b2d6

@devsargam @siinghd , Can you please review this

**Comment by palveVaishnav** [comment]
I have performed linting and formatting checks before committing, But there is some issue with the regex of 'payment.schema'.
and I haven't changed anything related to that and it appears again even after fixing it 
Screenshot (13)

**Comment by nischal-shetty2** [comment]
Already fixed in #955

**Comment by palveVaishnav** [comment]
> Already fixed in #955

yeah, but I am proposing a different UI for Q&A section. Let change the title from 'fix' to 'feature'

**Pull request closed without merging**
