### PR TITLE
fallback to video from appx

### PR DESCRIPTION
**Pull request by devsargam**

### CODE REVIEW

**Comment by mehul-srivastava** [comment]
I am curious why this was reverted back to the normal player. Any issues with the current approach?

**Comment by mehul-srivastava** [comment]
@devsargam?

**Comment by avparadox** [comment]
image
maybe we got it. am i correct @devsargam ? responsiveness issues? can't do full screen.

**Comment by mehul-srivastava** [comment]
> maybe we got it. am i correct @devsargam ? responsiveness issues? can't do full screen.

Is this on app.100xdevs? If yes, can you send me the link for the resource.
@avparadox

**Pull request merged**
