### PR TITLE
fix(dev): improve local development experience

### PR DESCRIPTION
**Pull request by devsargam**
### PR Fixes:
- Improves the seed command to not fail when executed once more
- Uses `process.env.LOCAL_CMS_PROVIDER` to provide mock users in middleware and signup

image
image

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by devsargam** [comment]
Also, @hkirat 
### Can I add a demo video which shows how to setup cms in the readme?

**Comment by nimit9** [comment]
Also, @devsargam @hkirat , can we add more data in the db while seeding? [Have a gist for this](https://gist.github.com/nimit9)

**Comment by devsargam** [comment]
Yeah would be really great

**Pull request merged**
