### PR TITLE
Fix: Error while replying to comments + clicking on timestamp + going back from reply

### LINKED ISSUE #587: bug: reply button not working in comments
Screenshot 2024-05-13 at 3 25 30 AM

### PR DESCRIPTION
**Pull request by mvp5464**
### PR Fixes:
- 1 Fixed error while clicking on replying button in comments.
- 2 Fixed error while clicking on timestamp in comments.
- 3 Fixed error while clicking on go back button from reply in comments.

Resolves #587 #602 #700 #712 #714 #715 #750 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

OLD

[replyError.webm](https://github.com/code100x/cms/assets/28997328/d516763b-ed58-4374-949d-a6fcf3f7b618)

NEW

[replyErrorNew.webm](https://github.com/code100x/cms/assets/28997328/88f68c61-8dde-4c9d-aaf3-8e5a94f7d9a0)

### CODE REVIEW

**Review by sasa5195 — APPROVED** [review]

**Comment by yash-kh** [comment]
@hkirat Can you merge this, I am working on one feature I need this to be fixed first.

**Comment by siinghd** [comment]
@mvp5464 Thank, tested it working fine.
Merging it now, for the bounty you must wait.
I will be submitting it, if it satisfies bounty requirements you will receive it :)

**Comment by siinghd** [comment]
@mvp5464 if you want you can also fix the multiple comments if you click the comment button quickly

**Comment by mvp5464** [comment]
> @mvp5464 if you want you can also fix the multiple comments if you click the comment button quickly

started working on it now.

**Comment by mvp5464** [comment]
### @siinghd , There is an error while commenting , reverted all the changes from this PR  still error persists , solving it 

Screenshot from 2024-06-15 23-25-03

**Comment by siinghd** [comment]
> ### @siinghd , There is an error while commenting , reverted all the changes from this PR still error persists , solving it
> Screenshot from 2024-06-15 23-25-03

Strange, tested it on local and was working fine

**Comment by mvp5464** [comment]
> > ### @siinghd , There is an error while commenting , reverted all the changes from this PR still error persists , solving it
> > Screenshot from 2024-06-15 23-25-03
> 
> Strange, tested it on local and was working fine

Error is specific to my machine, didn't figured out the problem yet but using incognito works so creating a new PR for duplicate comment

**Pull request merged**
