### PR TITLE
Fixed Share on LinkedIn button not visible initially on hover in light mode

### PR DESCRIPTION
**Pull request by JTiscodin**
### PR Fixes:
- 1 This fixes the problem where the share on linkedIn button is invisible in light mode.

Resolves #[Issue Number if there] 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding the same issue

### CODE REVIEW

**Comment by JTiscodin** [comment]
@hkirat can you look into this pr, the bug still exists and the pr hasn't been merged yet

**Comment by siinghd** [comment]
@JTiscodin  can you fix merge conflicts?

**Comment by JTiscodin** [comment]
@siinghd sure, I will fix it and then commit changes

**Comment by JTiscodin** [comment]
@siinghd Sir,  Thankyou for making the changes

**Pull request merged**
