### PR TITLE
feat: Progressive Web App (PWA)

### PR DESCRIPTION
**Pull request by Gautam-Hegde**
### This PR introduces Progressive Web App (PWA) functionality to our CMS, 
- users can install cms as a standalone app on their devices.(no more tab switches)
- w/ `next-pwa` package

 #### Lighthouse report
Screenshot (358)

Screenshot (356)

Screenshot (357)

Resolves #[Issue Number if there] 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by hkirat** [comment]
@devsargam can u review?

**Comment by devsargam** [comment]
@hkirat sure thing doing it rn

**Comment by devsargam** [comment]
@hkirat looks great can probably merge it!!!

**Comment by devsargam** [comment]
@Gautam-Hegde fix conflicts

**Pull request closed without merging**
