### PR TITLE
Twitter logo changed

### PR DESCRIPTION
**Pull request by Rimaru06**
#224 
used react-icons to changed the social media logo
icons_CMS

### CODE REVIEW

**Comment by devsargam** [comment]
Adding a 3rd party lib without permission might be annoying for the maintainer.

**Comment by Rimaru06** [comment]
in lucide there was no new logo of twitter

**Comment by Rimaru06** [comment]
and the icons that are used from lucide are deprecated that why i used react-icons

**Comment by hkirat** [comment]
Closing as @devsargam mentioned you shouldn't add a new library unless there's a dire need for it 
Comment by @aryanprince is also relevant

**Pull request closed without merging**
