### PR TITLE
Fix: watch history bug and lint.yml file

### LINKED ISSUE #1418: bug: some videos are not playing through watch history, it's gets redirected to home page
**Describe the bug**
While playing videos throw watch history, on some week videos it's get redirected to home page(like for a whole week video the page is not opening)
[video about the bug](https://github.com/user-attachments/assets/cef0c9ff-571b-4d52-8bbf-57a4c82a613e)

I guess the issue is, for some week videos, it is uploaded on more than 1 courses, and on that courses list some are not purchased by the user.
but, in this code we are using the courseId of the first course in the array, and maybe that course is not purchased by us.

file - src/components/watchhistoryclient
Screenshot 2024-10-04 173917

**To Reproduce**
1. just try to some videos to watch history, the video will not play for some weeks, for me(cohort 2) week 19, week 16 and some more weeks video are not working

**Expected behavior**
all the videos from the watch history should be played without any error

**Info (please complete the following information):**
 - chrome, brave
 - All

### PR DESCRIPTION
**Pull request by Prashant-flick**
### PR Fixes:
- fixed the watch history bug where video is not playing through watch history
- also fixed lint.yml file

Resolves #1418

[fixed bug video](https://github.com/user-attachments/assets/74368c72-bb8d-4885-aff7-f181ee646c12)

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by devsargam** [comment]
27 files changes can u reduce it

**Comment by Prashant-flick** [comment]
@devsargam 
 i only changed 3 files
1. lint.yml
2. watch-history/page.tsx
3. payoutMethods/schema.ts

and added one file .npmrc

rest of the file where linted and formated because of husky pre-commit

**Comment by devsargam** [comment]
Makes sense

**Comment by devsargam** [comment]
I will remove husky as of now and can u create a different pr

**Comment by Prashant-flick** [comment]
yeah sure

**Comment by Prashant-flick** [comment]
@devsargam I can proceed with making the pr without the need to removing Husky from the project

**Pull request closed without merging**
