### PR TITLE
Feature: added comments, added people can comment chapters, some improvements

### PR DESCRIPTION
**Pull request by siinghd**
Build: Working on local

Features: 
Comments: users can comment under the video/notion
Replies: Users can reply to a comment (Allowed only to depth 1 like youtube)
Upvotes/downvote: user can upvote or downvote the comment

Comment as chapter: user can comment chapters following the current format:

```
intro:
00:03 - Introduction to the topic
00:15 - Explaining the basics
00:30 - Deep dive into details
00:45 - 00:50 - Summary and conclusion
```

This is fully working and the comment is inserted as type `INTRO` and with flag approved to false.

Note*: In this PR admin part is not included but i was thinking to add a accept button or dropdown option where the admin can accept it. Second option would be to copy the comment id and on admin part make a input with comment id,adminpassword  and approve button.

On accepted the comment will be transformed to reflect the segments array and saved, the function to do it is already present thank to CHATGPT :)

Also user can click the timestamp in the comments and the video timestamp will be set to that.

---
Missing:
Admin part to accept the chapter comment
Admin can delete any comment
Users update/delete their comment

This is what i remember, ill update this if get to remember something else.

Improvemnts:
Many ui related improvement can be done
Maybe use react query for infinite scroll and remove current pagination

preview 

https://github.com/code100x/cms/assets/38940603/7345f45c-ed7a-4ced-94eb-a0177ceadd6b

### CODE REVIEW

**Comment by siinghd** [comment]
@hkirat can you look at this? would like to merge and do the admin part/some improvements

**Comment by siinghd** [comment]
Now admin can also approve the intro comments

preview:


https://github.com/code100x/cms/assets/38940603/91a3fe88-61c3-4568-bf96-6029d53f7f8f

**Comment by hkirat** [comment]
Beautiful

**Comment by hkirat** [comment]
Can u try deploying this to a local vercel @siinghd ?
Seeing this in the build pipeline on vercel
Screenshot 2024-02-10 at 4 28 33 AM

**Comment by siinghd** [comment]
@hkirat Was about to ping you, deploy failed... let me do it now :)

Thanks for the bounty veere <3

**Comment by hkirat** [comment]
Something is up with migrations 
Screenshot 2024-02-10 at 5 12 34 AM

Unsure if it broke here or in a different PR
But migrate is not working on a fresh DB

**Comment by siinghd** [comment]
@hkirat let me look at it

**Comment by hkirat** [comment]
Just need to migrate the DB I think I can figure this out @siinghd

**Comment by siinghd** [comment]
@hkirat any update on thi?

**Pull request merged**
