### PR TITLE
feat: downloading notes

### PR DESCRIPTION
**Pull request by nimit9**
### Feat #285 - Add a download button to notes

Had to modify css in the printing page for the printed document to look decent.

- Without css modifications: [Without Css Modifications.pdf](https://github.com/code100x/cms/files/14794983/Without.Css.Modifications.pdf)

[Screencast from 2024-03-29 01-40-41.webm](https://github.com/code100x/cms/assets/37402791/3c419dea-e49e-4d52-a460-c6e5a7b7cb2e)

- After Final Code: [After Final Code.pdf](https://github.com/code100x/cms/files/14795010/Final.Code.pdf)

[Screencast from 2024-03-29 01-39-18.webm](https://github.com/code100x/cms/assets/37402791/c84d9951-fc5a-462b-a3d6-3678a7f27cd0)

### CODE REVIEW

**Comment by devsargam** [comment]
hey @nimit9 
I think this is much optimized and elegant solution for print
https://tailwindcss.com/docs/hover-focus-and-other-states#print-styles

**Comment by nimit9** [comment]
Hey @devsargam , because I'm modifying notion classes, will have to add it with JS

**Comment by nimit9** [comment]
Thank you ser 🫡🫡 @hkirat

**Pull request merged**
