### PR TITLE
Feature: Play & Autoplay Next Video

### LINKED ISSUE #384: feature: Next Video Button
**Is your feature request related to a problem? Please describe.**
Whenever i complete a video i need to go back to the track and select the next video
**Describe the solution you'd like**
When the Video gets completed there will a button next to the mark as completed button that will take me to the next video , also we can add an autoplay the next video like thing

### PR DESCRIPTION
**Pull request by VK-RED**
### PR Fixes:

- 1  Added Autoplay next video, when the video ends , the next video will be autoplayed.
- 2  Also added a button, clicking on which plays the next video.

Resolves #384 

### Screencast

[Screencast from 17-04-24 08:00:32 PM IST.webm](https://github.com/code100x/cms/assets/130341088/6ae34790-eec9-495e-9dab-46675d40987f)

### Checklist before requesting a review
-  I have performed a self-review of my code
-  I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by VK-RED** [comment]
@hkirat can you check this out !!

**Comment by siinghd** [comment]
@VK-RED conflicts

**Comment by VK-RED** [comment]
@siinghd Resolving it sir !!

**Comment by VK-RED** [comment]
@siinghd  Prettier does not complain locally but seems to break in CI . Any thoughts in it ..

**Pull request closed without merging**
