### PR TITLE
ContentID correction

### LINKED ISSUE #752: Bug: Watching video from Week 2 but button shows Week 01.
Screenshot 2024-06-02 172310

### PR DESCRIPTION
**Pull request by iSouvikKhan**
### PR Fixes:
- When navigating to video/notes from different weeks, the focus should be on the week whose content is currently being viewed.

Resolves #752 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by iSouvikKhan** [comment]
@siinghd 

https://github.com/user-attachments/assets/12125943-5567-4f75-a68f-bbf8b19ffeb6

**Comment by iSouvikKhan** [comment]
@hkirat 

could you please have a look in this PR.

**Comment by siinghd** [comment]
thank you

**Comment by iSouvikKhan** [comment]
Thank you @siinghd,
I kind of dreaming, Lately I started with open source and this is the first PR which has been merged. Thank you again.

**Pull request merged**
