### PR TITLE
fix: download bug

### LINKED ISSUE #334: Notes not getting downloaded
Clicking on the download button opens a new tab but nothing downloads
Tried in chrome

### PR DESCRIPTION
**Pull request by mumin-khan**
### PR Fixes:
- 1 Fixes download button bug 
- 2

Have commented more details in the issue itself.
Resolves #334

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by mumin-khan** [comment]
image
Print() supported in android as well.
image
afterprint now supported in android and all major browsers

**Comment by hkirat** [comment]
Can u revert the lock file changes?

**Comment by mumin-khan** [comment]
@hkirat done.
Also you have closed a similar pr on code-daily.
I had mentioned the wrong issue number there but I am able to replicate the same bug on project.100xdevs.com as well.
https://github.com/code100x/daily-code/pull/308

**Comment by hkirat** [comment]
Seems to be working alreayd

**Pull request closed without merging**
