### PR TITLE
fix-#1190/full-screen-issue

### LINKED ISSUE #1190: bug: full screen issue
Screenshot 2024-09-11 at 5 29 10 PM

### PR DESCRIPTION
**Pull request by toufiqfarhan0**
### PR Fixes:
The navbar is causing the video to be cropped.

Before:

https://drive.google.com/file/d/115GaoI15Ee0-S3WgZ8s9x7sq5lIhJ8U-/view?usp=sharing

Resolves #1190 

After: 

https://drive.google.com/file/d/1xLNw2mg5O10dr9CvsfNg3LgdhqJ0PUkp/view?usp=sharing

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by MeerUzairWasHere** [comment]
what's fixed?

**Comment by toufiqfarhan0** [comment]
> what's fixed?

the nav bar is causing the problem here cropping the video when you zoom 100% I just made nav bar stick to top

**Comment by MeerUzairWasHere** [comment]
> > what's fixed?
> 
> the nav bar is causing the problem here cropping the video when you zoom 100% I just made nav bar stick to top

but video is still getting cropped.

**Comment by devsargam** [comment]
There are 7k changes. Closing for now. Resolve the conflicts and can u comeup with latest updated pr?

**Pull request closed without merging**
