### PR TITLE
Loading animation added when clicked on question card. Fix issue #1264

### PR DESCRIPTION
**Pull request by Adiflickzzz**
### PR Fixes:
- 1 Question card will show an pulse animation ( loading ) when clicked . 
Resolves #[1264] 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by wraith2009** [comment]
hey @Adiflickzzz  , just an advice brother .you show show before and after using a video or an image for clear understanding of what has changed and describe the change in more detail . althought what you explained is understandable . it's just a good practice to explain in detail about the changes .

**Comment by Adiflickzzz** [comment]
**This is the issue we were facing..**

https://github.com/user-attachments/assets/794b30f9-c8cb-4134-92e4-e0ee1e6e5b53

**Added an animation which make sure the user that an action is being performed !** 

https://github.com/user-attachments/assets/796a00f7-fa12-47d2-95c4-81c5eadeb097

> Making sure that its clear & understandable now !

**Comment by devsargam** [comment]
Thank you sir!!

**Comment by Adiflickzzz** [comment]
Most welcome sir !!

**Pull request merged**
