### PR TITLE
fixed time line for videos with no segments

### PR DESCRIPTION
**Pull request by mumin-khan**
### PR Fixes:
- 1 No timeline for videos without segments
- 2
 Reverted to the new video controls and Fixed  errors in it. Removed redundant code and added functionality to skip back and forward by double clicking which was missing in new video controls.
Resolves https://github.com/code100x/cms/issues/584
### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by mumin-khan** [comment]
image

**Comment by nimit9** [comment]
Please remove console logs.
This might be a hacky way of doing it. 

Try not to show the segments at all if there are no segments, and just show the seekbar.

**Comment by mumin-khan** [comment]
> Please remove console logs.
> 
> Also, This seems like a hacky way of doing it. Try not to show the segments at all if there are no segments, and just show the seekbar.

I am not showing segments.

**Comment by mumin-khan** [comment]
> > I am not showing segments.
> 
> I meant you're still making changes in the segment array

I agree this is somewhat hacky.
But as I said the code is is in such a way that there is no seekbar timelines are created for each segment with width equal to duration and events are registered for it.

**Comment by siinghd** [comment]
reopen, there are many conflicts

**Pull request closed without merging**
