### PR TITLE
Event listener

### PR DESCRIPTION
**Pull request by Kuzuri247**
### PR Fixes:
- 1 EventListener added in appbar

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by devsargam** [comment]
What is the change about? I am not getting it?

**Comment by Kuzuri247** [comment]
@devsargam addlistener is deprecated so I just replaced it with addEventlistener

**Comment by Kuzuri247** [comment]
is it too obvious(too short) or I am wrong or anything @devsargam

**Review by devsargam — APPROVED** [review]

**Comment by devsargam** [comment]
Thank you sir

**Comment by Kuzuri247** [comment]
Thanks sir

**Pull request merged**
