### PR TITLE
feat/search: Added search bar and other minor ui fix

### LINKED ISSUE #1175: bug: Search missing in the new UI
**Describe the bug**
- Search in the course content screen is missing which was present previously.
- Also the sidebar header is missing the background colour.

**Expected behaviour**
There must be a search bar in the UI and the sidebar header should have a background colour.

**Screenshots or GIFs**
Screenshot 2024-09-10 at 12 25 52 PM

### PR DESCRIPTION
**Pull request by ItsFlash10**
### PR Fixes:
- Added search bar back in the courses page and moved the siederbar trigger to the right since the sidebar is on the right side.
- Fixed the siderbar UI

Resolves #1175

@siinghd @devsargam @hkirat

https://github.com/user-attachments/assets/bb107666-603f-4d85-8646-4bd6c3989fe1

### Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by ItsFlash10** [comment]
@devsargam This PR includes a fix for the search API to return results for only the courses that a user has purchased, currently, it's showing the result from the entire DB as you mentioned.

**Comment by devsargam** [comment]
Where does this pr stands with the new addition of https://github.com/code100x/cms/pull/1205
Is this still needed @ItsFlash10?

**Comment by ItsFlash10** [comment]
> Where does this pr stands with the new addition of #1205 Is this still needed @ItsFlash10?

This solves what you mentioned about current search is searching the entire courses in the db instead of user-specific purchases.

**Comment by devsargam** [comment]
Thank you sir

**Pull request merged**
