### PR TITLE
feat: Add email domain suggestions to signin component

### LINKED ISSUE #843: feature:  Enhance Login Page with password Focus and Email Auto-Complete
1. Email to Password Auto-Focus:
   - When a user enters their email and presses the Enter key, the focus should automatically shift to the password field.
   - This removes the touching of mouse after entering the email
  
 2. Email Domain Auto-Complete:
    - If the user enters an email address without the '@' symbol, automatically append '@gmail.com' to the end of the input.
    - since the gmail is popular domain that everyone uses
    - This feature removes the tedious task of typing of @gmail.com everytime during login

### PR DESCRIPTION
**Pull request by vijaysingh2219**
### PR Fixes: #843 
- Implemented dynamic email domain suggestions based on user input.
- Filtered suggested domains based on partial matches after '@' in email input.
- The code changes are in accordance with the requirements specified in https://github.com/code100x/cms/pull/841#issuecomment-2267227798.

Resolves #843  

### Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by siinghd** [comment]
@vijaysingh2219 will check this and get back

**Comment by hkirat** [comment]
very nice PR
@siinghd @devsargam for review

**Comment by devsargam** [comment]
Checking

**Review by devsargam — APPROVED** [review]
Works perfectly locally

https://github.com/user-attachments/assets/b8ce8232-48fe-4ad0-b498-a832871c15fe

**Comment by devsargam** [comment]
I do not. Waiting for hkirat or hsingh to merge it. 👌

**Comment by devsargam** [comment]
ok @vijaysingh2219 this pr will be merged soon. I will check with the guys

**Comment by siinghd** [comment]
@vijaysingh2219 can you fix locks files?

**Review by devsargam — APPROVED** [review]

**Comment by devsargam** [comment]
hey @siinghd @hkirat can we merge this?

**Comment by devsargam** [comment]
@vijaysingh2219 thank you sir!!!

**Pull request merged**
