### PR TITLE
feat: updated the video play background color

### PR DESCRIPTION
**Pull request by pankaj-2503**
image
Added background color on the video play bar for better ui . Hence fixes issue #74

### CODE REVIEW

**Comment by sahilsuman933** [comment]
Please remove both of the lock files from the commit.

**Comment by pankaj-2503** [comment]
@sahilsuman933  do you mean package-lock.json file . I thought it would be required so installed is previously.

**Comment by sahilsuman933** [comment]
Yeah. Please remove the `yarn.lock` and `package-lock.json` from the commit. Also, you don't need dotenv package as by default nextjs supports it. So, please remove changes related to that as well.

Docs for reading about environment variables: https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables

**Comment by pankaj-2503** [comment]
> Yeah. Please remove the `yarn.lock` and `package-lock.json` from the commit. Also, you don't need dotenv package as by default nextjs supports it. So, please remove changes related to that as well.
> 
> Docs for reading about environment variables: https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables
> 
> // @pankaj-2503

I have updated the PR as you said earlier.

**Pull request closed without merging**
