### PR TITLE
Feature/linking questions to video

### LINKED ISSUE #862: feature: Connect the question to the video (High priority - valuable bounty)
We already have a platform for questions at [100xdevs](https://app.100xdevs.com/questions), but it is currently underutilized.

To increase engagement, I propose connecting questions to specific videos. Here's a plan for implementation, which can be further improved for a better outcome:

### Proposed Features:

1. **Linking Questions to Videos**:
    - When creating a question, users should have the option to link it to a specific video.
    - Users can either search for a video or select one from a searchable dropdown menu. 
    - This feature should be optional, as we still want to allow questions without associated videos.

2. **Video Integration**:
    - Each video should have a button that, when clicked, redirects the user to all questions related to that video.

3. **Database Changes**:
    - Add an optional `video_id` field to the question table to store the associated video ID.

4. **Future Improvements (V2)**:
    - Implement notifications to a specific Discord channel when a new question is created.

---

Note: These are initial thoughts, and any further improvements are welcome! (do not limit to only initial thoughts!)

### PR DESCRIPTION
**Pull request by Sajal0208**
This PR Adds:
- 1 When creating a question, users now have the option to link it to a specific video.
- 2 Users can search a video from the search bar present inside the `Add Questions` Dialog.
- 3 This feature is optional, as we still want to allow questions without associated videos.
- 4 Each video has a button that, when clicked, redirects the user to all questions related to the video.
- 5 Made the necessary database changes
- 6 Dynamically calculating height of the MEditor to fix the overflow of the Modal Components in Questions Page

Resolves #862 

Screenshots Below: 

Screenshot 2024-08-09 at 7 21 24 PM

Screenshot 2024-08-09 at 10 16 47 PM

Screenshot 2024-08-09 at 10 16 53 PM

Screenshot 2024-08-09 at 7 51 02 PM

Screenshot 2024-08-09 at 7 51 13 PM

- [✅] I have performed a self-review of my code
- [✅ ] I assure there is no similar/duplicate pull request regarding same issue

Open to any changes/suggestions/commits to this PR. 
For contact, DM me on Twitter: https://x.com/DewanganSajal

### CODE REVIEW

**Comment by siinghd** [comment]
@Sajal0208 what if we have 500 videos? how the dropdown will look? 
can we improve it further?

**Comment by Sajal0208** [comment]
@siinghd Should I group it like this - 

Course Dropdown ->Week Dropdown -> Then Videos
Or anyother suggestions?

**Comment by siinghd** [comment]
> @siinghd Should I group it like this -
> 
> Course Dropdown ->Week Dropdown -> Then Videos Or anyother suggestions?

I have already mentioned this in the issue post, try to look at it buddy

**Comment by Sajal0208** [comment]
> > @siinghd Should I group it like this -
> > Course Dropdown ->Week Dropdown -> Then Videos Or anyother suggestions?
> 
> I have already mentioned this in the issue post, try to look at it buddy

Apologies, I might have skipped that point. 

The above commit fixes the issue

**Comment by siinghd** [comment]
@Sajal0208 looking promising, will wait little see other PRs too, in while improve with any idea u have

**Comment by Sajal0208** [comment]
Hey @siinghd, any updates on the bounty?

**Comment by Sajal0208** [comment]
@siinghd , can you please merge this PR?

**Comment by siinghd** [comment]
@Sajal0208 i saw zero prs other than this for that issue, will test it today and merge it

**Comment by Sajal0208** [comment]
> @Sajal0208 i saw zero prs other than this for that issue, will test it today and merge it

@siinghd Alright, makes sense. Let me know if we need to add something else in the PR.

**Comment by Sajal0208** [comment]
Hey @siinghd, you still haven't merged this PR 😅

**Comment by siinghd** [comment]
@Sajal0208 can you fix the conflicts ?

**Comment by Sajal0208** [comment]
> @Sajal0208 can you fix the conflicts ?

Hey @siinghd, I have resolved the conflicts

**Comment by Sajal0208** [comment]
Hey @siinghd, a gentle reminder to merge this PR

**Comment by Sajal0208** [comment]
Hey @siinghd, I know you are running busy but this PR is on hold since a month. Can you please take a look at the same. I have already resolved the conflicts 3 times and I don't know why the resolve conflict button is not working now. Please have a look at this whenever you have time. 

Thanks.

**Pull request closed without merging**
