### PR TITLE
fixed responsiveness + refactored the UI for better UX

### LINKED ISSUE #992: bug: Address UI bugs + Refactor the UI + Fix Responsiveness
**Describe the bugs**

1. The Appbar is not taking full width as shown in ss:
image

2. When the size is at about tablet screen it is not responsive.
image

3. The design layout for the Course Card is inconsistent. And thumbnail images does not appear for some of the courses.
image

4. There should be less gap between the side nav items, and proper color branding for dark and light mode. The side menu toggle button does not have any hover effects.
image
 
 5. While logging out the user once the user has clicked on logout button there is this UI being displayed. Instead the user should be directly redirected to the 100xdevs homepage. Also there is an alignment issue between side bar and app bar. 
image

6. The video card is not taking full width when the screen width is decreased, it is not responsive. Also the course nav bar and the sidenav bar should automativally closed for responsiveness/ mobile friendly design when the user decreases the width of the screen.
refer the ss and video below:
image

7.Improper use of cursor pointer.

https://github.com/user-attachments/assets/8d65cc59-16fd-4bfd-9b1a-616f12b21fd1

8. On landing page the mobile nav is visible for laptop screen alongside Login and Join Now button. (It should only be displayed for screen smaller than md breakpoint (768px) and the other burrons should disappear)

https://github.com/user-attachments/assets/8bbeaae4-9406-4985-a39a-6ec1fb796ed6

9.Question screen has inconsistent UI styling and responsiveness.
https://github.com/user-attachments/assets/c297ed44-c952-40fb-aa81-77b98860f11d

https://github.com/user-attachments/assets/4343d785-37b2-4bc3-b179-d370003989f9

**Expected behavior**
A clear, concise and responsive design across the application for better UX.

**Additional context**
Refer the figma file, I would like to propose these design for enhancing the UX.
https://www.figma.com/design/7YxkpBVl3FQFiWCNuSYMgx/100xDev-UI-Refactoring?node-id=0-1&t=6EKWvTlUqJBm0l4L-0

Can I be assigned to these issue @hkirat  @siinghd ?

### PR DESCRIPTION
**Pull request by Harit007x**
### PR Fixes:

- [x] The Appbar is not taking full width.

- [x] When the size is at about tablet screen it is not responsive.
 
- [x] The design layout for the Course Card is inconsistent.
 
- [x] There should be less gap between the side nav items, and proper color branding for dark and light mode. 
 
- [ ] While logging out the user once the user has clicked on logout button there is this UI being displayed. 
 
- [x] Instead the user should be directly redirected to the 100xdevs homepage. Also there is an alignment issue between side bar and app bar.
 
- [x] The video card is not taking full width when the screen width is decreased, it is not responsive. Also the course nav bar and the sidenav bar should automatically closed for responsiveness/ mobile friendly design when the user decreases the width of the screen.

- [x] Improper use of cursor pointer.
 
- [x] On landing page the mobile nav is visible for laptop screen alongside Login and Join Now button. (It should only be displayed for screen smaller than md breakpoint (768px) and the other burrons should disappear)

- [x] Question screen has inconsistent UI styling and responsiveness

- [x] Remove the framer motion animations for tooltip and use shadcn tooltip for better performance

- [x] Make the sidebar automatically closed at lg(large) breakpoint for responsive design, implement logic to close the side bar if user clicks outside the sidebar area. (only to work for width lesser than lg breakpoint)
 
- [x] Make the view content screen responsive and refactor the course card and content card components.
 
- [x] Make the course sidebar navigation component responsive.

- [x] Added missing macther path values in middleware to redirect the user to the login screen after logout. 

It Resolves #992  

@siinghd @hkirat

### CODE REVIEW

**Comment by Harit007x** [comment]
@siinghd The PR #1010 is ready for the review, it addresses all the critical UI, responsiveness issues. Tried my best to follow standard practices while resolving the issues. Let me know if there is a room for an improvement.

Please find the attched video for preview:

https://github.com/user-attachments/assets/3009e447-de84-4fe3-8675-e80a7bbd8889

**Comment by siinghd** [comment]
Ui looks different

**Comment by Harit007x** [comment]
> Ui looks different

**Comment by Harit007x** [comment]
> Ui looks different

I tried to tweak the UI a little, it does look a little different but I think it promotes better UX.
What do you think ?

**Comment by Harit007x** [comment]
> > Ui looks different
> 
> I tried to tweak the UI a little, it does look a little different but I think it promotes better UX.
> What do you think ?
> 
> @siinghd 

Awaiting your response @siinghd , it would be great if you can review the entire PR and if it proves useful then you can tell me for the adjustments it requires.

**Comment by Harit007x** [comment]
> > > Ui looks different
> > 
> > 
> > I tried to tweak the UI a little, it does look a little different but I think it promotes better UX.
> > What do you think ?
> > @siinghd
> 
> Awaiting your response @siinghd , it would be great if you can review the entire PR and if it proves useful then you can tell me for the adjustments it requires.

@siinghd I'm still waiting for your response. Could you please provide an actionable answer? This would help me gain clarity on what steps to take.

**Pull request closed without merging**
