### PR TITLE
downloading notes now working

### LINKED ISSUE #422: bug: Notes not downloading
before fixing the bug

https://github.com/code100x/cms/assets/123832227/1749605e-cc2e-4896-91f2-fb5ad8261bab

after fixing the bug

https://github.com/code100x/cms/assets/123832227/0d57e666-4202-458f-b1c8-00f5e4ad5c93

### PR DESCRIPTION
**Pull request by mayankgb**
### PR Fixes:
fixes  #422

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by hkirat** [comment]
So it has always worked locally, it fails when deployed on https for some reason
Unsure if this will actually fix it
Can u confirm if it works on an internet facing URl by using somehting like ngrok?

**Comment by mayankgb** [comment]
@hkirat but window.close() function automatically closes the window before the download feature appear on the screen that's why it's not working i think

**Comment by mayankgb** [comment]
@hkirat 

using ngrok download feature is working

https://github.com/code100x/cms/assets/123832227/bd9fb174-776b-4da3-9520-c26e1447cd3d

**Comment by mayankgb** [comment]
@hkirat 

using ngrok download feature is working


https://github.com/code100x/cms/assets/123832227/2849f279-a775-4eb9-a177-2ba3ebe8c716

**Comment by mayankgb** [comment]
window.close() is remove

**Pull request merged**
