### PR TITLE
fix: fixed #460 comments filter not working

### LINKED ISSUE #460: bug: not able to filter comments
**Describe the bug**
When trying to filter comments its redirect to the home page.

**To Reproduce**
1. Go to any video
2. Above comments, try to filter them

**Expected behavior**
It should filter comments based on the given filter selection.

**Screenshots or GIFs**
image

**Info (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Kartik1110**
### PR Fixes:
- Fixed comments filter not working

Resolves #460 #468 

### Checklist before requesting a review
- [ x] I have performed a self-review of my code
- [ x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by Kartik1110** [comment]
Hey @hkirat can you please check this PR?

**Comment by kmaity-9563** [comment]
hey, @Kartik1110 the issue remains there, are you still working on it?

**Comment by Kartik1110** [comment]
@kmaity-9563 The issue is fixed, but PR is not merged yet.
@hkirat please check

**Comment by Kartik1110** [comment]
Hey @hkirat , Please check this PR as this issue is still not working on the website.

**Comment by siinghd** [comment]
already done, closing

**Pull request closed without merging**
