### PR TITLE
Requested Design revamfication

### PR DESCRIPTION
**Pull request by An525ish**
### PR Fixes:
- 1 [add app sidebar](https://github.com/code100x/cms/commit/0ab3591fd1e378f8413ce9c45434f12ead6c4a04)
- 2 [fix course page](https://github.com/code100x/cms/commit/95747676eecc2706d5cf579227af5a108fc323a0)
- 3 [fix all design bugs (includes theme and design fixes)](https://github.com/code100x/cms/pull/900/commits/beacff0d3ceb36eb0f2d43cc3b6d44047e407619)

Resolves #888

### Checklist before requesting a review
- [✅] I have performed a self-review of my code
- [✅] I assure there is no similar/duplicate pull request regarding same issue

https://github.com/user-attachments/assets/0a9a297c-f3aa-4675-a580-d5119ce2cc2d

### CODE REVIEW

**Comment by An525ish** [comment]
> ### PR Fixes:
> * 1 [add app sidebar](https://github.com/code100x/cms/commit/0ab3591fd1e378f8413ce9c45434f12ead6c4a04)
> * 2 [fix course page](https://github.com/code100x/cms/commit/95747676eecc2706d5cf579227af5a108fc323a0)
> * 3 [fix all design bugs (includes theme and design fixes)](https://github.com/code100x/cms/pull/900/commits/beacff0d3ceb36eb0f2d43cc3b6d44047e407619)
> 
> Resolves #888
> 
> ### Checklist before requesting a review
> * [✅] I have performed a self-review of my code
> * [✅] I assure there is no similar/duplicate pull request regarding same issue
> 
>  Take.your.development.skills.from.0.to.100.and.join.the.100xdevs.community.-.Google.Chrome.2024-08-18.19-57-35.mp4

@hkirat it works or anything else is needed ?

**Comment by siinghd** [comment]
@An525ish looks good, fix lock

**Comment by An525ish** [comment]
> @An525ish looks good, fix lock

can you please elaborate what lock are you talking about ?

**Comment by An525ish** [comment]
> > @An525ish looks good, fix lock
> 
> can you please elaborate what lock are you talking about ? @siinghd

**Pull request closed without merging**
