### PR TITLE
fix:fixed the view-all-chapter popup

### PR DESCRIPTION
**Pull request by palveVaishnav**
### PR Fixes:
- 1 converted the popup to a dropdown which will not affect the size of video.
- 2 Move the title and 'lecture slides' button up for ui consistency. (personal opinion )

Resolves #888  #1075 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

## Note :
- This PR is related to https://github.com/code100x/cms/pull/1111.
- If Sidebar has to stay on left  as designed in #888, then adding chapter dropdown would look better then what we already have.
- Else if  #1111 is merged , then you can ignore this PR . 

https://github.com/user-attachments/assets/3112d74f-5cda-4b12-ba78-d53e2d97b560

@siinghd Can you please review this PR.

### CODE REVIEW

**Comment by palveVaishnav** [comment]
@vijaysingh2219 &  @devsargam can you please review this PR.

**Comment by devsargam** [comment]
Design can be improved. Pls can u do a better design?

**Comment by palveVaishnav** [comment]
> Collaborator
Sure, On it .

**Comment by palveVaishnav** [comment]
How about this one @devsargam ,

https://github.com/user-attachments/assets/3d93de6f-48a7-4c63-8707-5f87d0c5e5c9

**Pull request closed without merging**
