### PR TITLE
Feat: Setup a github bot that dispatches events to discord channel

### LINKED ISSUE #188: Create a docker bot
That posts anytime there is 
1. An issue created
2. An bounty dispensed on PR merge
on a channel on discord

### PR DESCRIPTION
**Pull request by devsargam**
Fixes #188

### This feature deserves a separate repo `code100x/100xbounty-bot`
Ref: https://github.com/devsargam/100xbounty-bot

Install the github app: https://github.com/apps/100xbountybot

Create prs and issues to test: https://github.com/devsargam/100xbounty-bot

Setup a discord webhook, it won't until you self host the bot

### CODE REVIEW

**Comment by devsargam** [comment]
https://github.com/code100x/cms/assets/76874341/8249aae5-99af-4ebf-a33b-ef593163213f

**Comment by devsargam** [comment]
image
image

**Comment by hkirat** [comment]
Can you PR it here - https://github.com/code100x/100xbounty-bot ?

**Comment by hkirat** [comment]
nvm seems like https://github.com/code100x/cms/pull/225 does the job

**Comment by devsargam** [comment]
@hkirat do u want to hit a pr or are u happy with #225?

**Comment by hkirat** [comment]
https://github.com/code100x/cms/pull/225 is good enough for now

**Pull request closed without merging**
