### PR TITLE
Feat: Progressive Web App (PWA) 

### PR DESCRIPTION
**Pull request by Gautam-Hegde**
### This PR introduces Progressive Web App (PWA) functionality to our CMS, 
- users can install cms as a standalone app on their devices.(no more tab switches)
- w/ `next-pwa` package
- optimized with proper icons for windows, ios and android devices.

*PWA in action*

 #### Lighthouse report
Screenshot (358)

Screenshot (356)

Screenshot (357)

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by Gautam-Hegde** [comment]
@hkirat awaiting for a review.

**Comment by nimit9** [comment]
Is there a need for so many icons? Isn't this over optimisation?

**Comment by Gautam-Hegde** [comment]
> Is there a need for so many icons? Isn't this over optimisation?

yep, but icons are actually super light and optimized for PWA, gen using std. PWA builder. I don't see it as overoptimization cuz its an accessibility ft

**Comment by Gautam-Hegde** [comment]
closing due to inactivity.

**Pull request closed without merging**
