### PR TITLE
fix: video player being responsive in all sizes (#144)

### LINKED ISSUE #136: When closing the sidebar using the cross button the video box is not responsive
https://github.com/code100x/cms/assets/68225661/ec6cf524-c7a1-432c-9ddc-d8602bf8384c

### LINKED ISSUE #144: Video height should be restricted when user has full screened the video
Video overflowsfrom the bottom, should be max of the current height of the window
Screenshot 2024-03-03 at 11 52 03 AM

### PR DESCRIPTION
**Pull request by devsargam**
Fixes #144 
Fixes #136

### CODE REVIEW

**Comment by hkirat** [comment]
Can you share what it looks like after you've full screened it?

**Comment by devsargam** [comment]
@hkirat here you go
https://github.com/code100x/cms/assets/76874341/7d82aba2-492e-44c7-a449-5cfb1f78d6c4

**Comment by hkirat** [comment]
/bounty $50
Thankyou!

**Comment by devsargam** [comment]
Thanks sireee @hkirat 🙇

**Comment by YunusShaikh29** [comment]
@devsargam can you tell me how did you added more videos in the website?

**Pull request merged**
