### PR TITLE
fix: The theme toggle button appears twice.

### PR DESCRIPTION
**Pull request by mortale2004**
### PR Fixes:
- 1 I have fixed the theme toggle button which appears two times by removing from the dropdown.
- 2 Formatted the all project to fix the formatting issue.

The issue was #1314

### CODE REVIEW

**Comment by devsargam** [comment]
Can u fix conflicts. Also provide some good screenshots

**Comment by mortale2004** [comment]
Sure why not

**Comment by mortale2004** [comment]
Here is the screenshot image

**Review by devsargam — APPROVED** [review]

**Comment by devsargam** [comment]
Thank you sir

**Pull request merged**
