### PR TITLE
Feature/commentype

### LINKED ISSUE #238: Type of  Comment DropDown shows incorrect name on change.
In the comment section the user have option to select and change the type of comment.
image
On change to Intro Comments the drop down value is marked with the code rather than description shown below.
image

This should not happen and On change the value should remain as that of the description shown in the drop down initially.

### PR DESCRIPTION
**Pull request by Anurag12133**
### PR Fixes:
- 1 Comment TYpe to default for Intro comments
- 2 Single compnent of page

Resolves #238  

### Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X
Screenshot from 2024-07-27 20-44-11
] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by siinghd** [comment]
Sir what's with the changes?

**Comment by Anurag12133** [comment]
@siinghd Actually when click on Intro comment , the bar where this text was showed as INTRO only but in case of All comments it is showing what its default. So i changed the type of Intro comment to default so the text is same as Intro comments not only INTRO

**Comment by siinghd** [comment]
@Anurag12133 why so many changes? can you fix that?

**Comment by Anurag12133** [comment]
@siinghd yes sure

**Pull request closed without merging**
