### PR TITLE
fixed card selection using keyboard

### LINKED ISSUE #1360: bug: not able to select cards as a keyboard user
**Describe the bug**
As a keyboard user, I'm not able to select and navigate to the weeks page by selecting the cards as the card is not receiving focus.

**To Reproduce**
1. Head to https://app.100xdevs.com/
2. Use keyboard to navigate the site (using tab).
3. Navigate to /courses/[id] page
4. And tab through the elements and notice that week cards won't receive focus and not able to select any week.

**Expected behavior**
Using tab to move focus to week cards, they should receive focus and moving focus onto them and pressing enter should take user to that specific page. 

**Screenshots or GIFs**

https://github.com/user-attachments/assets/9371320f-3ebb-46ff-92be-d1eda13d0f31

**Info (please complete the following information):**
Browser [e.g. Edge ]
Version [e.g. 129.0.2792.65]

### PR DESCRIPTION
**Pull request by Jatin123lodhi**
### PR Fixes:
-  Fixed the issue where cards were not selectable using the keyboard.

Resolves #1360 

### Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by devsargam** [comment]
Can u show screenshort/recording of the change?

**Comment by Jatin123lodhi** [comment]
Uploading Screen Recording (10-1-2024 3-15-01 PM).mp4…

**Comment by Jatin123lodhi** [comment]
https://github.com/user-attachments/assets/e4d69fc3-86bf-4c9a-a07e-87797945f011

**Comment by Chityalaakhil** [comment]
Looks good. Thanks.

**Comment by devsargam** [comment]
thank u

**Pull request merged**
