### PR TITLE
Made sidebar Header Sticky

### LINKED ISSUE #1084: style: Fix title "course content" to stick to the top.
## Is your issue related to a problem? Please describe.
The title of the page, currently labeled "Course Content," does not remain fixed at the top when scrolling. This issue causes the title to disappear from view, making it difficult to navigate back to the section header while scrolling through lengthy content.

## Describe the solution you'd like
I would like the "Course Content" title to be styled so that it sticks to the top of the page, remaining visible as users scroll through the content. This will improve navigation and ensure the title is always accessible.

## Describe alternatives you've considered

- **Make the title sticky** : Use CSS `position: sticky` to keep the title fixed at the top while scrolling.
- **Move the title outside the scrolling div** : Place the title outside of the scrolling content container to ensure it remains visible.
- **Make the title fixed** : Use CSS `position: fixed` to keep the title always visible at the top of the viewport.

image
<br>
&nbsp&nbsp&nbsp |
<br>
&nbsp&nbsp \/
<br>
image

### PR DESCRIPTION
**Pull request by zenithexe**
### PR Fixes:
- 1 Made the Content Sidebar Heading Sticky

Resolves #1084 
 
https://github.com/user-attachments/assets/319e3bdc-a0cb-4c53-858e-439453a17e74

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by csgaikwad** [comment]
Are you working on the failed checks?

**Comment by devsargam** [comment]
Np it's a conflict between husky and prettier u don't need to worry

**Comment by csgaikwad** [comment]
> I have been trying to solve the `failed check` for quite some time now, from what I have realized, I think something is broken in the main repo itself. When I try to clone and install(`npm i`) the `code100x/cms` repo, it gives the same error.
> 
> Also, as you can see I have made changes only to the `Sidebar.tsx` file.
> 
> @hkirat @devsargam you guys should look into this.

i feel like we are supposed to use `pnpm install` rather than `npm i`

**Comment by csgaikwad** [comment]
@zenithexe  they are saying don't use npm as they are trying to migrate to pnpm

**Comment by siinghd** [comment]
thank you sir

**Pull request merged**
