### PR TITLE
Added authentication to content update apis.

### PR DESCRIPTION
**Pull request by paahaad**
### PR Fixes:
- There are two api used update the videoMetadata :  ``` api/admin/updatecontent ``` and ``` api/admin/contentmetadata ```. rn anyone with or without logging can change or delete the videoMetadata based on content id. Added the admin-password check for the same.

Test: this was my api payload that cleared all the link from columns for endpoint :- contentmetadata 
```
{
    "contentId" : 3,
    "updates": {}
}
```

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by paahaad** [comment]
cc: @devsargam  @siinghd

**Comment by devsargam** [comment]
Will check the prior one as well as this today if possible

**Comment by hkirat** [comment]
/bounty Rs 15000
Thanks for this and the existing PRs. Keep em coming

**Comment by devsargam** [comment]
When did we switch to rs @hkirat?

**Comment by devsargam** [comment]
don't think the bot manages to capture those

**Comment by hkirat** [comment]
recent addition.

**Comment by hkirat** [comment]
@paahaad whats ur upi?

**Comment by ItsFlash10** [comment]
God damn xD

**Comment by paahaad** [comment]
@hkirat Thank you so much sir. 9324726059@axl.

**Pull request merged**
