### PR TITLE
fix/1028-active-menu-indicator

### LINKED ISSUE #1028: feature: Active menu indicator on sidebar for better UX & usability
**Is your feature request related to a problem? Please describe.**

Small UX or usability issue, as there is no indicator for user to see the **active menu option** on the side bar menu.

**SS:**

image

**Describe the solution you'd like**

There should be some indicator like shown in the SS below that would enhance usability and make navigation clearer for users.

**SS:**

image

### PR DESCRIPTION
**Pull request by hxdy-1**
### PR Fixes:
- 1 Implemented Active menu option highlight in the sidebar for all corresponding routes

Resolves #1028 

**SS:**

image

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by devsargam** [comment]
This is nice ux. @hxdy-1 will get to review this when @keshav-exe finishes the new ui update

**Comment by hxdy-1** [comment]
@devsargam shall i raise a new PR according to the new UI? cuz the issue I reported is also there in new UI

**Comment by devsargam** [comment]
Yeah

**Comment by devsargam** [comment]
@hxdy-1

**Pull request closed without merging**
