### PR TITLE
 fixed the multiple comments error if you click the comment button quickly

### PR DESCRIPTION
**Pull request by mvp5464**
### PR Fixes:
- 1  fix the multiple comments if you click the comment button quickly
- 2 Solved merged conflict error, which already present in the code-base
 
### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by siinghd** [comment]
@mvp5464 can we do the same for all the inputs? upvote downvote etc?

**Comment by mvp5464** [comment]
working on it.

**Comment by mvp5464** [comment]
Done @siinghd , any other changes ?

**Comment by siinghd** [comment]
Thank you sir

**Pull request merged**
