### PR TITLE
Show proper message and hide scrollbar/pagination when response is empty

### PR DESCRIPTION
**Pull request by ajeeshRS**
### PR Fixes:
- 1 Display proper message when response is empty
- 2 Conditionally render scrollbar and pagination components

### Testing
- Used sample data to simulate responses and validate the changes.

### Screenshots
Before :
Take-your-development-skills-from-0-to-100-and-join-the-100xdevs-community (3)
After : 
Take-your-development-skills-from-0-to-100-and-join-the-100xdevs-community (6)

Resolves #[Issue Number if there] 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by siinghd** [comment]
@ajeeshRS can you remove package-lock?

**Comment by ajeeshRS** [comment]
done

**Comment by ajeeshRS** [comment]
Hi @siinghd ,

I’ve removed the package-lock.json as requested. Could you please review the PR when you have a moment? Thanks!

**Comment by ajeeshRS** [comment]
@siinghd do i need to make any changes for this ?

**Pull request closed without merging**
