### PR TITLE
fix loading error in /discord/redirect

### LINKED ISSUE #692: bug: discord error when user denied Oauth process ( show loding )
**Describe the bug**
When you cancel the Oauth authorization From discort Oauth page, it shows loading

**To Reproduce**
1. click on join discord button from profile dropdown and cancel the Oauth process 
2. It shows loading

**Expected behavior**
It should show error  like user denied the access 

Screenshots or GIFs
image

**Info (please complete the following information):**
 Browser  Chrome
 Version 124.0.6367.208 (Official Build) (64-bit)

**Additional context**
/discord/redirect page exrect the code params from url but when user cancel the auth there is no code prams to exract leaving
loading to for the user

### LINKED ISSUE #720: bug: certificate typo
Screenshot 2024-05-28 at 5 31 49 PM

### PR DESCRIPTION
**Pull request by manishpali17**
### PR Fixes:
- FIx loading error when user cancels access to Discord

Resolves #692
Resolves #720

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by AyushShivhare79** [comment]
Hey the PR was already created #728

**Comment by AyushShivhare79** [comment]
He just copied the exact code of mine and even the certificate png is copied @hkirat 
This is my PR #728

**Comment by manishpali17** [comment]
Hi @AyushShivhare79,

why are you whining like a child? I made a mistake by not checking the PR request first, but here is the conversation with ChatGPT. 

chatgpt


I didn't copy your code; I just asked ChatGPT for help, and it gave me the same response. It's not my fault. I can even say that you copied your code from ChatGPT because it gave me the exact solution, lol. 

After this, I also checked to see if the code was working correctly, and I found the UI was out of place, so I made changes to the UI as well.

**Comment by AyushShivhare79** [comment]
@manishpali17 ChatGPT can't align the text to right position in image are you able to run the test case locally ser? The Png text size almost same as mine. Although The PR was already raised.

**Comment by manishpali17** [comment]
@AyushShivhare79  bro, if I had seen your comment on my PR, I would have closed it myself. I don't like to take credit for your work.

And here it is now. You can see that I used ChatGPT 4.0, which also takes images. It gave me the exact code. I can't share the conversation due to some error, but here is the screenshot. I used the original image, so the size is the same.

chat

**Comment by Smnthjm08** [comment]
@AyushShivhare79  [can you explain this](https://github.com/code100x/cms/issues/720#issuecomment-2137856418)

**Comment by AyushShivhare79** [comment]
@Smnthjm08 What ser?

**Comment by Smnthjm08** [comment]
> @Smnthjm08 What ser?

I tried to do the changes. But I couldn't test the certificate. Can I know how to dot that

**Comment by AyushShivhare79** [comment]
@Smnthjm08  You can connect me on discord i got you on OSS-chat I will teach you how to generate certificate for local test user or any user for testing but this issue is already resolved so IG you should work on something else.

**Pull request closed without merging**
