### PR TITLE
made navbar smaller, moved course content button inside navbar, removed lower appbar

### LINKED ISSUE #1551: bug: Screen area is filled too much by navbar on the top and appbar on the bottom. Video size is not fit for the screen size
**Describe the bug**
Screen area is filled too much by navbar with show content button on the top and appbar on the bottom. It makes difficult to navigate through the course contents. Video size is not fit for the screen size.

**To Reproduce**
1. Sign in and open any course content
2. Most of the screen is taken up by the navbar and appbar.
3. Play any video without entering into fullscreen. Video content is not much visible.

**Expected behavior**
1. navbar can have smaller height.
2. appbar can be completely removed from the bottom because all the options are already available in the profile button in the navbar.
3. video size can be smaller.

**Screenshots or GIFs**
image
image

### PR DESCRIPTION
**Pull request by ankit0tech**
made navbar smaller, moved course content button inside navbar, removed lower appbar.

Resolves #1551

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by ankit0tech** [comment]
The fix will be visible as shown in the video below:
https://github.com/user-attachments/assets/4bef559d-62d5-44d3-b651-1ec5738d74e1

**Comment by devsargam** [comment]
Hey can you resolve the conflicts

**Comment by ankit0tech** [comment]
Hi @devsargam, I have resolved the merge conflicts. Can you please review the PR?

**Comment by devsargam** [comment]
This has been already resolved closing

**Pull request closed without merging**
