### PR TITLE
fixed three dots menu on comments shown to all users

### LINKED ISSUE #1259: bug: Able to click on 3 dots (options) for comments not authored by the user
**Description:**  
There is a bug where users can click on the 3 dots (options menu) for comments that they did not author. This action should be restricted to the comment's author only. 

**Steps to Reproduce:**
1. Log in as a user.
2. Navigate to a course video with comments.
3. Find a comment authored by another user.
4. Attempt to click on the 3 dots/options menu for that comment.

**Expected Behavior:**  
Only the author of the comment should be able to click on the 3 dots.

**Actual Behavior:**  
Any user can click on the 3 dots/options menu for comments not authored by them.

**Attachments:** 
image
image

### PR DESCRIPTION
**Pull request by karranx**
### PR Fixes:
- 1 Three dots menu on comments shown to all users and not just the owner of the comment

Resolves #1259 

### Checklist before requesting a review
- [ yes ] I have performed a self-review of my code
- [ yes ] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by MeerUzairWasHere** [comment]
lol, 17 files
are you kidding me?

**Comment by Dhaneshwarguiyan** [comment]
@MeerUzairWasHere It is happening due to Code Linting and Formatting I have experienced the same ,I had changed only three lines and after running running npm run lint:check/fix and same for the format These many files have changed

**Comment by Dhaneshwarguiyan** [comment]
Even without running the npm run lint:fix/format:fix, when commiting the changes it happens by default

**Comment by Dhaneshwarguiyan** [comment]
and the linting is so irregular ,
is this an **issue** or it is made like that
Screenshot from 2024-09-20 10-42-40
You can see in the above file the imports go to the same line same line and on different line for some imports

**Comment by karranx** [comment]
@MeerUzairWasHere it also fixes linting and makes the code more in-line with the rest of the code base. without this, it will fail the linting check.

**Comment by devsargam** [comment]
Closign in favour of #1260

**Pull request closed without merging**
