### PR TITLE
Update LoginGate.tsx

### PR DESCRIPTION
**Pull request by Aryam2121**
Removed unnecessary justify-center flex classes by using text-center for centering text. Moved the sign-in logic into a separate function (handleSignIn) for better readability. Combined the two div elements into one, using mb-4 for margin-bottom spacing. Cleaned up the code for better organization and readability.

### CODE REVIEW

**Comment by Aryam2121** [comment]
sir you merge my code so its correct its say i  contribute in this or not?

**Comment by hkirat** [comment]
it is correct

**Comment by hkirat** [comment]
This is a simple contribution tho I wouldn't tout it on twitter if that's what you're thinking of doing :)

**Comment by Aryam2121** [comment]
no sir i just asking only my code is correct or not

**Comment by devsargam** [comment]
Your change is good for project.

I am not him but ur code does so less compared to the grand schema of things. It is a nice start but nothing too drastic.

**Comment by Aryam2121** [comment]
one silly question sir gave me bounty for this ?

**Comment by devsargam** [comment]
Nope. But it was a nice one dude.

Work hard for passion money will come eventually dw🤞🏻

**Comment by Aryam2121** [comment]
i was joking i will also not take money  for this

**Pull request merged**
