### PR TITLE
fix/video controls not visible in full screen

### PR DESCRIPTION
**Pull request by Akash1000x**

### CODE REVIEW

**Comment by devsargam** [comment]
Hey @Akash1000x your pr looks great but ideally use cn(cslx + tw-merge) to be consistent with tailwind with conditional styling

**Comment by devsargam** [comment]
https://github.com/code100x/cms/blob/e95389726d2d78d90a647acbeb6f45dc1e68a670/src/lib/utils.ts#L7

**Comment by giteshsarvaiya** [comment]
Hello @Akash1000x , I believe for mobile users, you should Still do conditional rendering. 
Cos in mobile (if not using fullscreen) the player controls will be visible and distract the user.
You can incorporate this using "sm:" and "md:" as tailwindcss utility classes.

**Comment by Akash1000x** [comment]
@giteshsarvaiya  if the user needs to change the video resolution, speed, volume, etc., it's important to show the controls

**Pull request merged**
