### PR TITLE
Bounty dashboard with github account verification

### LINKED ISSUE #673: feature: bounty dashboard
**Is your feature request related to a problem? Please describe.**
Unable to tracks bounties

**Describe the solution you'd like**
Track all the bounty PR by user and admin

### PR DESCRIPTION
**Pull request by mvp5464**
### PR Fixes:
- 1 Bounty dashboard for users and admin
- 2 Link github account with the cms account
- 3 Listen to bounty message with github webhook

Resolves #673 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

## Linking github account
[B_userLogin.webm](https://github.com/code100x/cms/assets/28997328/ad057cad-1106-4c67-a855-68b428083226)

## Different dashboard for both User and admin
[B_adminUser.webm](https://github.com/code100x/cms/assets/28997328/dce2a5d6-6579-4d45-90fe-332df4a59bfa)

## Listen to bounty message and update to database
[B_addBounty.webm](https://github.com/code100x/cms/assets/28997328/79b0dab3-969d-449b-897a-947f6c1cc730)

## All Features 
- One bounty per PR (to avoid duplicate bounty)
- Users can link their 100xdevs account with their github to get all bounty info
- If account is not linked still bounty info will be added to DB
- Admin can see them and when account gets linked all bounty info will be shown to that user
- Two different dashboard for user and admin
- Admin can check user info and bounty info for any user
- user and admin can see total bounty PR and Total amount of such bounty
- Conversion from USD to Rupee (Change daily)
- Can support pay on click by adding payment info of users and payment gateway
- Get information about is bounty paid or not 

## Need to add email to read-only for github provider (so we can get email  (even if hidden) when user signin with github
 
Screenshot

### CODE REVIEW

**Comment by mvp5464** [comment]
### Confirmation message to github after successful DB. Also message for duplication of Bounty
[B_confirmComment.webm](https://github.com/code100x/cms/assets/28997328/5c35c9b1-f2f1-4092-8d85-0c4ab4e00db3)

**Comment by mvp5464** [comment]
Hi @devsargam @nimit9 , could you review this pr specially the GithubLogin.tsx page where user Links his account to github. 
Is there any better approach for it. Or any other way to improve this pr.

**Comment by nimit9** [comment]
Hey, we have a bounty-hook repo which tracks the bounties, https://github.com/code100x/bounty-hook
This might not be needed

**Comment by mvp5464** [comment]
Yes but I think it would be difficult to connect 100xdevs user with their github on bounty-hook. This pr also allow to dispatch bounty and keep track of it. 
Or is their any downside of having bounty in this repo. then should I make this changes to bounty-hook repo and remove from here.

**Comment by nimit9** [comment]
Yeah, you can, but these features might not be needed.

@hkirat can answer better on this though.

**Comment by mvp5464** [comment]
may be you are right, thank you

**Comment by hkirat** [comment]
feature looks decent , but yeah integrate the BE with bounty-hook

**Comment by mvp5464** [comment]
OK sir, working on it

**Comment by ebe25** [comment]
hey mvp cool feature boss, are currently working change the BE to the bounty webhook?

**Comment by mvp5464** [comment]
> hey mvp cool feature boss, are currently working change the BE to the bounty webhook?

Thanks for the appreciation brother. Yes, getting some errors, but will solve it.

**Comment by mvp5464** [comment]
@hkirat Sir, Integrated BE with bounty-hook.

**Pull request closed without merging**
