### PR TITLE
Added highlighting for current active content on the sidebar

### LINKED ISSUE #256: Highlight courses sidebar for the currently running content similar to YouTube.
Currently there is no way to know on which content we are at on the courses sidebar, this creates a bad user experience. 
It would be great , if we could implement currently running content highlighting similar to YouTube.

Screenshot from 2024-03-22 08-58-59

I'd like to work on it, if we decide to proceed with this issue.

Please let me know your thoughts on this.

### PR DESCRIPTION
**Pull request by haddercone**
fixes #256 

This PR adds UI enhancements for the courses Sidebar component to keep track of currently active content.
It lets the user know where they are the course. 

**Video reference:**

[demo-1.webm](https://github.com/code100x/cms/assets/32171406/14865a87-1241-4ecd-9589-2556e21bd143)

### CODE REVIEW

**Comment by hkirat** [comment]
pleaes fix merge conflicts, colors are very bad please clean them as well

**Comment by haddercone** [comment]
> pleaes fix merge conflicts, colors are very bad please clean them as well

On it!

**Comment by haddercone** [comment]
@hkirat fixed merge conflicts with better colours.
Please let me know your thoughts on this.

**Comment by haddercone** [comment]
Updated demo

[demo-3.webm](https://github.com/code100x/cms/assets/32171406/b1786b11-02ed-47cb-97b5-39bb34afd6d0)

**Pull request merged**
