### PR TITLE
fixed the cert design !!

### LINKED ISSUE #596: bug: revert to this type of cert
WhatsApp Image 2024-05-13 at 10 06 08

@TanmayDhobale

### PR DESCRIPTION
**Pull request by TanmayDhobale**
### PR Fixes:
@hkirat 
/certificate not working on app.100x and on  local also  and not able to see certificate so change logic in cert.ts and make false and its worked !!! check that pls  ( const courses = purchases.filter((x) => x.certIssued === false); ) 

Resolves #596 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

Screenshot 2567-05-13 at 4 53 05 PM

### CODE REVIEW

**Comment by TanmayDhobale** [comment]
for an seed file pls check this pr #599

**Comment by TanmayDhobale** [comment]
btw its give 4 certificate idk why maybe bcs of an 5 course we have

**Comment by TanmayDhobale** [comment]
> NO HELP CREDIT? 😣 @TanmayDhobale 
Special thanks to @piyushhsainii  for wasting time, I'm kidding

**Comment by KadlagAkash** [comment]
@TanmayDhobale Can we do it in Dark Mode...!!

**Comment by hkirat** [comment]
/bounty $50
I think we need to do the same thing for the pdf as well

**Comment by TanmayDhobale** [comment]
> /bounty $50 I think we need to do the same thing for the pdf as well

umm pdf ???

**Comment by TanmayDhobale** [comment]
> > /bounty $50 I think we need to do the same thing for the pdf as well
> 
> umm pdf ??? @hkirat

**Comment by hkirat** [comment]
You can download pdf as well

**Comment by hkirat** [comment]
That design is still the old one

**Comment by TanmayDhobale** [comment]
yoo sry i did mistake its 0 to 1  now its 0 to 100 
update

**Comment by TanmayDhobale** [comment]
Screenshot 2567-05-28 at 12 58 37 AM
@hkirat

**Comment by KadlagAkash** [comment]
@TanmayDhobale Can we update the 100xdevs  

- Text : **100xDevss**
- Font-Face : Be Vietnam Pro
- Weight : Semi-Bold

**Comment by AyushShivhare79** [comment]
@TanmayDhobale  I fixed this issue of showing the wrong course #728 

And @hkirat Solved the pdf issue as well on #738

**Pull request merged**
