### PR TITLE
Added keyboard functionalities of playback speed and volume control to video

### PR DESCRIPTION
**Pull request by dhruvilmehta**
Resolves issue #43 and also adds some extra functionalities for volume.

Added functionalities:
Press `Shift+,` to decrease playback speed.
Press `Shift+.` to increase playback speed.
Press `Shift+ArrowUp` to increase volume.
Press `Shift+ArrowDown` to decrease volume.

https://github.com/code100x/cms/assets/68022411/d03fb30e-ed82-43b8-8c11-1f4a9a194c70

### CODE REVIEW

**Comment by hkirat** [comment]
Can u revert package lock c hanges?

**Comment by dhruvilmehta** [comment]
Reverted changes in package-lock.json

**Comment by hkirat** [comment]
Sorry meant both the lock files, please revert yarn.lock as well

**Comment by dhruvilmehta** [comment]
Done.

**Pull request merged**
