### PR TITLE
Done #14(Sticky sidebar) #3(Chapters, this one still need some improvements aka thumbnails), #32 hamburger in appbar

### PR DESCRIPTION
**Pull request by siinghd**
This pr fixes the issues: #32 #3 #14 

Set sidebar to be  sticky at the top on scroll
Added chapters, missing thumbnails (maybe in future)
Moved hamburger to the AppBar instead of body

Preview:

https://github.com/code100x/cms/assets/38940603/e794e2e3-9c84-4b8c-8b23-d721b9cc88d3

Build:

Working on local

### CODE REVIEW

**Comment by hkirat** [comment]
Thankyou @siinghd 
Do u mind extracting just the sidebar bit in this one? 
I merged in chapters from a different PR which we might have to stick to because eventually it'll look similar to tammy ai
Screenshot 2024-02-02 at 2 26 19 AM

**Comment by siinghd** [comment]
Didn't saw #86ccf4bc-1eaf-499e-ab8e-9f3c40fef289 , i think the way i have done looks more cleaner... depends on your preference :)

**Comment by siinghd** [comment]
> Thankyou @siinghd Do u mind extracting just the sidebar bit in this one? I merged in chapters from a different PR which we might have to stick to because eventually it'll look similar to tammy ai Screenshot 2024-02-02 at 2 26 19 AM

Sure :)

**Comment by hkirat** [comment]
Dropdowns might get tricky with it being on the left . 
It also saves space tho. Unsure which one I love more

**Comment by siinghd** [comment]
> Dropdowns might get tricky with it being on the left . It also saves space tho. Unsure which one I love more

I would prefer my approach hahahha, it's just intuitive don't have to look at multiple things

**Comment by hkirat** [comment]
Some merge conflicts in there could u look at them?

**Comment by siinghd** [comment]
> Some merge conflicts in there could u look at them?

looking at them :)

**Comment by siinghd** [comment]
@hkirat should be fine now :)

**Comment by nimit9** [comment]
Also one more thing @hkirat @siinghd instead of sending json for segments, can we send it like how YouTube does it? 
Like this:
00:00 Segment 1
04:46 Segment 2
01:04:06 Segment 3

It'll be easier for anyone who's adding the segments instead of adding the json?

We can store the json while hitting the backend the same way,  just changing the input part? 
I'd like to work on it if you think that this might be a better way.

**Comment by siinghd** [comment]
> Also one more thing @hkirat @siinghd instead of sending json for segments, can we send it like how YouTube does it? Like this: 00:00 Segment 1 04:46 Segment 2 01:04:06 Segment 3
> 
> It'll be easier for anyone who's adding the segments instead of adding the json?
> 
> We can store the json while hitting the backend the same way, just changing the input part? I'd like to work on it if you think that this might be a better way.

Isn’t this just how you see it in frontend? 
I don’t think YouTube does something different in the backend. 
You can create the admin section for adding the segments to the backend as that is missing. 
From the person imputing the segments you can ask them however you want after that just convert the time format to seconds and it should work fine.
Also adding json is just sending the json payload to the backend via post.

**Comment by nimit9** [comment]
> > Also one more thing @hkirat @siinghd instead of sending json for segments, can we send it like how YouTube does it? Like this: 00:00 Segment 1 04:46 Segment 2 01:04:06 Segment 3
> > 
> > It'll be easier for anyone who's adding the segments instead of adding the json?
> > 
> > We can store the json while hitting the backend the same way, just changing the input part? I'd like to work on it if you think that this might be a better way.
> 
> Isn’t this just how you see it in frontend? 
> I don’t think YouTube does something different in the backend. 
> You can create the admin section for adding the segments to the backend as that is missing. 
> From the person imputing the segments you can ask them however you want after that just convert the time format to seconds and it should work fine.
> Also adding json is just sending the json payload to the backend via post.

Yes, the section is already added, you can check it at `/admin/userFlow`

The existing input asks for a json input, instead of how YouTube asks to add the segments.

Rest all remains the same

**Comment by siinghd** [comment]
@nimit9 Saw it ;)

Yes that can be improved, you can make an array of objects just like the end segments. 
Something like:
Input start time, input end time, input title, button add segments 

final button -> submit -> here you just pass the array aka json payload ;)

**Comment by nimit9** [comment]
> @nimit9 Saw it ;)
> 
> Yes that can be improved, you can make an array of objects just like the end segments. 
> Something like:
> Input start time, input end time, input title, button add segments 
> 
> final button -> submit -> here you just pass the array aka json payload ;)

I feel adding start time and end time both is unnecessary as the starting time for next segment would be ending for the previous one, 
so that is redundant input. 

Just adding the time in the form of hh:mm:ss/mm:ss(if less than 1 hour) would be good for UX as the admin won't have to keep calculating seconds for every segment (imagine adding start as 3769 and end as 3963)

**Comment by siinghd** [comment]
> > @nimit9 Saw it ;)
> > Yes that can be improved, you can make an array of objects just like the end segments.
> > Something like:
> > Input start time, input end time, input title, button add segments
> > final button -> submit -> here you just pass the array aka json payload ;)
> 
> I feel adding start time and end time both is unnecessary as the starting time for next segment would be ending for the previous one, so that is redundant input.
> 
> Just adding the time in the form of hh:mm:ss/mm:ss(if less than 1 hour) would be good for UX as the admin won't have to keep calculating seconds for every segment (imagine adding start as 3769 and end as 3963)

On frontend to the user you can ask them however you want I think haha ;)

**Comment by nimit9** [comment]
> > > @nimit9 Saw it ;)
> > > Yes that can be improved, you can make an array of objects just like the end segments.
> > > Something like:
> > > Input start time, input end time, input title, button add segments
> > > final button -> submit -> here you just pass the array aka json payload ;)
> > 
> > I feel adding start time and end time both is unnecessary as the starting time for next segment would be ending for the previous one, so that is redundant input.
> > 
> > Just adding the time in the form of hh:mm:ss/mm:ss(if less than 1 hour) would be good for UX as the admin won't have to keep calculating seconds for every segment (imagine adding start as 3769 and end as 3963)
> 
> On frontend to the user you can ask them however you want I think haha ;) 

Yeah that's what I was asking. Since it'll be an admin (@hkirat or someone from his team), I'm not sure what they prefer, so thought of asking them first)

**Comment by hkirat** [comment]
Yeah we want to crowdsource segments as soon as possible. So might be more convinient for people to do segments similar to youtube.
Before that we need to add a `description` section below the video where the segments can be put (similar to youtube)
Ideally the closer we can get to YT the better

**Comment by siinghd** [comment]
@hkirat this can be merged and closed i think

**Comment by hkirat** [comment]
Yeah holding in merging until https://github.com/code100x/cms/issues/45 is fixed to avoid re-deployment

**Comment by nimit9** [comment]
> Yeah we want to crowdsource segments as soon as possible. So might be more convinient for people to do segments similar to youtube. Before that we need to add a `description` section below the video where the segments can be put (similar to youtube) Ideally the closer we can get to YT the better

@hkirat 
I'd like to work on it, just not sure how could we get the thumbnails for each segment.

**Comment by hkirat** [comment]
There is a `thumbnailmosaicUrl` in the database. 
I think @siinghd built that

**Comment by siinghd** [comment]
> > Yeah we want to crowdsource segments as soon as possible. So might be more convinient for people to do segments similar to youtube. Before that we need to add a `description` section below the video where the segments can be put (similar to youtube) Ideally the closer we can get to YT the better
> 
> @hkirat I'd like to work on it, just not sure how could we get the thumbnails for each segment.

Hi you can find that here:  https://github.com/siinghd/player-custom-seekbar

If you want to look at the working example https://nextjs-videothumb.hsingh.site
Also the backend is still up here https://api-videothumb.hsingh.site (https://api-videothumb.hsingh.site/video?fileId=1234)

The backend let you generate the thumbnails of a video, normally it will look like so 
1234_composite

**Comment by nimit9** [comment]
Thanks @hkirat @siinghd, I'll take a look

**Comment by nimit9** [comment]
> @hkirat 
> I'd like to work on it, just not sure how could we get the thumbnails for each segment.

@hkirat do we really need thumbnails? As they'd be just random points in a video with code which anyways won't be visible in the thumbnail.

**Pull request merged**
