### PR TITLE
chore: Improve site's metadata and optimise images

### PR DESCRIPTION
**Pull request by devsargam**
Changes:
- [x] Adds [`sharp`](https://www.npmjs.com/package/sharp) to optimise image during build
- [x] Custom metadata to properly embed website in social media like: Discord, Twitter, Instagram, etc
- [x] Improves SEO with proper title and description in metadata

Before:
image

After:
image

### CODE REVIEW

**Comment by devsargam** [comment]
@hkirat are you happy with current favicon?

Seems like a lot of people are annoyed with that.
Would love to improve that in this pr too.

**Comment by nimit9** [comment]
Hey, instead of hardcoding same things like title and description, you could have a config for it and import it everywhere.

**Comment by devsargam** [comment]
hey @nimit9, thanks for your feedback. Your opinion sounds a lot better than what I am doing. Making the changes.
Thanks 🚀

**Comment by hkirat** [comment]
Can u get rid of the merge conflicts @devsargam

**Comment by devsargam** [comment]
@hkirat done

**Comment by devsargam** [comment]
🙇

**Pull request merged**
