### PR TITLE
Made video-player and video-chapters responsive

### LINKED ISSUE #1034: bug: Chapter's component became unresponsive with the new UI changes
**Describe the bug**
image

**To Reproduce**
Split the screen to half size and the bug is visible. 

**Expected behavior**
Previously the chapters' component would go down but now it competes for space.

**Info:**
 - Browser : Firefox (PC)

### PR DESCRIPTION
**Pull request by zenithexe**
### PR Fixes:
- The Video player will take the entire space, if chapters are closed.

Resolves #1034  

https://github.com/user-attachments/assets/6c89ef98-2c0a-43ae-ba73-f9d7cb06d714

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by SujithThirumalaisamy** [comment]
Can you please add the logic to show the refresh database button on the expansion of the sidebar. And not on the shrink of if? The button is making the sidebar not to go to its default size.

**Comment by SujithThirumalaisamy** [comment]
Why `schema.ts` have a lot of noise?

**Comment by zenithexe** [comment]
@SujithThirumalaisamy for some reason, when I commit my code, extra brackets `( )` added to the regex. That's why it has some noise.

**Comment by zenithexe** [comment]
> Can you please add the logic to show the refresh database button on the expansion of the sidebar. And not on the shrink of if? The button is making the sidebar not to go to its default size.

I think this was fixed and merged in some other PR.

**Comment by SujithThirumalaisamy** [comment]
> @SujithThirumalaisamy for some reason, when I commit my code, extra brackets `( )` added to the regex. That's why it has some noise.

You can use 'git commit --no-verify -m ""'

**Pull request merged**
