### PR TITLE
Fix urgent #45

### LINKED ISSUE #45: Login broke
https://github.com/code100x/cms/commit/116bd23a88d58a0f33bcf9bd09ec62ce0c4f3791 broke login

email isn't reaching the backend correctly. Have rolled back prod but should be fixed ASAP

### PR DESCRIPTION
**Pull request by siinghd**
Fix #45 

Looking at https://github.com/code100x/cms/blob/main/src/lib/auth.ts, Backend requires `username` field and not `email` as json payload.

This also has #34

### CODE REVIEW

**Comment by shreyas0924** [comment]
@siinghd  Sry, I did a silly mistake. Hope ur solution fixes the code

**Review by shreyas0924 — CHANGES_REQUESTED** [review]
Is it possible to add a check that if the user is already authentcated, then redirect to home page.

```
 if(session?.data?.user){
    router.push('/')
   }
```

**Comment by siinghd** [comment]
> Is it possible to add a check that if the user is already authentcated, then redirect to home page.
> 
> ```
>  if(session?.data?.user){
>     router.push('/')
>    }
> ```

Done, moved current signin process to seperate client component. This way the page is rendered on server and can check the session for server redirect instead of client redirect

**Comment by shreyas0924** [comment]
> > Is it possible to add a check that if the user is already authentcated, then redirect to home page.
> > ```
> >  if(session?.data?.user){
> >     router.push('/')
> >    }
> > ```
> 
> Done, moved current signin process to seperate client component. This way the page is rendered on server and can check the session for server redirect instead of client redirect

Good one!!

**Comment by Neon-20** [comment]
Why are we not handling everything inside a middleware.ts file , that would be a cleaner approach. All the protected routing specific things. ref: https://github.com/Neon-20/Authify/blob/ec47c66a90b1115c9d7f209933ef7ae3ebf3f542/middleware.ts (Something like this)

**Pull request merged**
