### PR TITLE
fixed the video loading problem

### PR DESCRIPTION
**Pull request by devsargam**

### CODE REVIEW

**Comment by saurabhraghuvanshii** [comment]
@devsargam sir why did  you change max-width frame 850px to 1350px . as we see videos as overflow

**Comment by devsargam** [comment]
can you screenshot it?

**Comment by saurabhraghuvanshii** [comment]
Screenshot 2024-12-03 223823
Screenshot 2024-12-03 223854

**Comment by devsargam** [comment]
I see. I will figure out a good solution

**Pull request merged**
