### PR TITLE
Added course purchases and auth system

### LINKED ISSUE #169: Add purchases, payment information
Right now, a lot of the backend (user auth and course purchases) is deligated to appx
We want to create a strategy where courses can be bought in house
This will require some schema design so if you're thiniking of working on this please post the schema and approach first

### PR DESCRIPTION
**Pull request by dhruvilmehta**
### PR Fixes:
- 1 Added user registeration system
- 2 Purchase with Razorpay

Resolves #169  

### Checklist before requesting a review
- [X] I have performed a self-review of my code
- [] I assure there is no similar/duplicate pull request regarding same issue
Similar to @devsargam but added a little tweaks to DB schema and URLs for buying courses.

UI is broken for now but can be done soon once this is approved.

Approach:

DB Schema
Untitled-2024-04-02-1559

Flow of payment
Untitled-2024-04-02-1610

Note: 8 files just have formatting changes due to prettier check while committing.

### CODE REVIEW

**Comment by dhruvilmehta** [comment]
Receipts page (users can see bought courses and receipt id:

image

Buy Courses page:

image

Course Details section (where the user can see about the course content):
Razorpay pops up when clicked on Pay Now Button

image

**Comment by hkirat** [comment]
This is great, will review later today

**Comment by dhruvilmehta** [comment]
Hey @hkirat , are you also interested in integrating crypto payments with coinbase commerce api? If yes, I can start working on that.

**Comment by dhruvilmehta** [comment]
Hey @hkirat, are you still interested in this feature?

**Comment by hkirat** [comment]
yes this is top priority for me to review
will probably do tom

**Comment by hkirat** [comment]
So the signup logic here is useful, I'll be copying that over
The razorpay logic has some issues. 
We'll be using a webhook from razorpay to tell us if a purchase is made, and when made it should populate the `Purchase` table - https://github.com/code100x/cms/blob/main/prisma/schema.prisma#L26

I'll be shelving the PR for now (not closing it as we may need payments in the future). But we will have to get rid of the client side call here - and replace it with a webhook from rzp - https://github.com/code100x/cms/pull/324/files#diff-68bf6bcd40c0526800dac7b625b2c2ecaee8433b54f07d37738e3155cd1fe501R55

**Comment by devsargam** [comment]
Hey kirat just in case this could be helpful
ref: https://github.com/code100x/cms/pull/175

**Comment by dhruvilmehta** [comment]
Hi @hkirat , I have added a webhook for razorpay. You can test this webhook on localhost with `ngrok`. It gives you a public url for your localhost:3000. You have to put the public url on razorpay and receive events for `payments.captured` event.

**Comment by siinghd** [comment]
@dhruvilmehta will be testing it ASAP

**Comment by dhruvilmehta** [comment]
Hi @siinghd , are you testing it? If everything seems fine, we can merge it before Web3 cohort launch. Just the UI part would be remaining that can be done ASAP.

**Pull request closed without merging**
