### PR TITLE
FIX: #722

### LINKED ISSUE #722: bug: Share on LinkedIn button not visible initially on hover in light mode.
**Describe the bug**
The LinkedIn button in share certificate is not visible initially when hovered over in light mode, but becomes visible after hovering.

**To Reproduce**
1.  Switch to light mode.
2.  Hover over the LinkedIn button.
3.  Observe that the button is not visible initially and then becomes visible.

**Expected behavior**
The LinkedIn button should be clearly visible in light mode both before and after hovering.

**Screenshots or GIFs**
bug-certificate

**Info (please complete the following information):**

**Additional context**
This issue affects the visibility of the LinkedIn button in light mode works fine in dark mode

### PR DESCRIPTION
**Pull request by Anurag12133**
### PR Fixes:
- 1
- 2

Resolves #722 

### Checklist before requesting a review
- [ X ] I have performed a self-review of my code
- [ X ] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by siinghd** [comment]
can be merge

**Comment by siinghd** [comment]
@Anurag12133 probably will close this tho, as https://github.com/code100x/cms/pull/730 is the first pr that solve's the issue.

**Comment by Anurag12133** [comment]
Oh i got it

**Comment by siinghd** [comment]
this can be close in favor of https://github.com/code100x/cms/pull/730

**Comment by siinghd** [comment]
closing , fixed in : https://github.com/code100x/cms/pull/730

**Pull request closed without merging**
