### PR TITLE
Minor ui and theme enhancements

### PR DESCRIPTION
**Pull request by zzzzshawn**
### PR Fixes:
- 1 Added smooth theme transition
https://github.com/user-attachments/assets/869e0fd4-c48d-4067-b05f-75a8947507ea

- 2 Enhanced "No bookmarks saved" component by adding a fun meme
image

-3 Added shadow to course cards to give dimensions to the site
pr3

### Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by Chityalaakhil** [comment]
Hey @zzzzshawn, the theme swither animation looks cool. Can you do the same animation in reverse also when you switch from dark to light?

**Comment by zzzzshawn** [comment]
> Hey @zzzzshawn, the theme switcher animation looks cool. Can you do the same animation in reverse also when you switch from dark to light?

It works both ways sir, just had a video recording issue

heres the updated video:

https://github.com/user-attachments/assets/b21529a7-0fc3-45ad-8d48-2527ee59ac25

**Comment by zzzzshawn** [comment]
@Chityalaakhil

**Comment by Chityalaakhil** [comment]
Awesome!

**Comment by devsargam** [comment]
Yeah I recommend to remove husky completely

**Comment by zzzzshawn** [comment]
> Hey, not able to figure out your changes because of all the formatting.
> 
> @devsargam I'm seeing this in many PR's, do u know if there's any new code formatting rule added recently? Also, all these prs might get conflicts if anyone's pr is merged. How do u proceed?

@Chityalaakhil how do you suggest i show u the changes ive made now?

**Comment by zzzzshawn** [comment]
added noBookmark.svg
added NoBookmark.tsx
edited BookmarkView.tsx
edited ThemeToggler.tsx
edited Navbar.tsx
edited Courses.tsx
edited CourseCard.tsx
edited globals.css

this is everything ive changed

**Comment by devsargam** [comment]
Sorry had to close it it just had a lot of conflicts

**Comment by devsargam** [comment]
Can u make a smaller pr please

**Comment by zzzzshawn** [comment]
> Can u make a smaller pr please
sure ill do it later today

**Pull request closed without merging**
