### PR TITLE
fix(course-view): implement resizable and sheet for course view

### LINKED ISSUE #401: bug: sidebar is not consistent
**Describe the bug**
currently the sidebar is not consistent, it is getting shorter width for some videos and perfect for some

**Expected behavior**
need to be consistent sidebar for all videos

**Screenshots or GIFs**
Screenshot 2024-04-13 at 9 34 21 PM
Screenshot 2024-04-13 at 9 34 52 PM

**are you working on this issue?**
no, anyone can pickup this if @hkirat feels this is an issue and approve it

### PR DESCRIPTION
**Pull request by devsargam**
### PR Fixes:
- Implement a sheet for the sidebar which makes it responsive in all sizes
- Setup a resizable to resize the video and timestamps which was weird in some cases

Resolves #401

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by devsargam** [comment]
Siderbar Sheet
image

**Comment by devsargam** [comment]
Resizable video and timestamp
image

**Comment by TanmayDhobale** [comment]
bro ive fix the Siderbar Sheet in #381 can u check

**Comment by devsargam** [comment]
@TanmayDhobale didn't see that this is for a demo contribution video.

**Comment by TanmayDhobale** [comment]
> @TanmayDhobale didn't see that this is for a demo contribution video.

Got it got it

**Pull request closed without merging**
