### PR TITLE
make video fitted as screen

### LINKED ISSUE #1523: bug: video not fitted as window
when I open video it not fit as window some parts are downs and some are ups
Screenshot 2024-10-28 234237
Screenshot 2024-10-28 234151

**Expected behavior**
when a web open like YouTube a video should be fit and view whole in format and when when adjust frame of window video should be adjust according to it.

***One more fixture  can be added ***
 there should be cinema mode for adjust video to horizontal for fit screen as Like in YouTube.

### PR DESCRIPTION
**Pull request by saurabhraghuvanshii**
### PR Fixes:
- 1 fixed ratio for lecture on full web page 
- 2

Resolves #1523  

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### before PR

https://github.com/user-attachments/assets/befdfd8c-a1d7-4fa3-b6fb-39b50e723097

###After Solving this issue

https://github.com/user-attachments/assets/6f419cbf-1395-472c-8f78-bdd3b723a022

### CODE REVIEW

**Comment by saurabhraghuvanshii** [comment]
@devsargam review this.

**Comment by saurabhraghuvanshii** [comment]
@hkirat check this

**Comment by mdex-geek** [comment]
Make it respnsive

**Comment by saurabhraghuvanshii** [comment]
@mdex-geek you mean for every type of screen

**Comment by saurabhraghuvanshii** [comment]
@mdex-geek check it try to make responsive  set maxWidth to 850px so in large screen it does not overflow

https://github.com/user-attachments/assets/b9e16617-aab8-44a7-932a-eae17bfa3504

**Comment by devsargam** [comment]
Thank you sir

**Comment by saurabhraghuvanshii** [comment]
@devsargam thanks sir for merge , I am very happy today , this is my first pr got merged

**Pull request merged**
