### PR TITLE
Fixes:#1278 removed the /usr/src/app/node_modules volume from docker-…

### LINKED ISSUE #1278: bug: Installation Error via Docker in Windows bcoz of node modules Volume
**Describe the bug**
I was trying to set the project locally as per the readme instruction via docker when I did docker-compose up everything ran fine but at end it throws Error: ENOENT: no such file or directory, open '/usr/src/app/.next/BUILD_ID'

**To Reproduce**
1. Follow set up instruction using docker

**Environment**
1. Windows 11

**Screenshots or GIFs**
2024-09-20_11h25_07

https://github.com/user-attachments/assets/0f5e334c-e0d2-4f32-90f1-0f902dd6982f

### PR DESCRIPTION
**Pull request by Anish-bit04**
### PR Fixes:
- This pull request addresses an issue where including a volume for /usr/src/app/node_modules in the docker-compose.yml file causes dependency issues and prevents the Next.js application from building correctly within a Docker container.

### Problem
The current configuration mounts the entire project directory and creates a separate volume for node_modules:

Resolves #1278 

### Checklist before requesting a review
- [ ] I have performed a self-review of my code
image

- [ ] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by Adiflickzzz** [comment]
https://github.com/user-attachments/assets/87304386-867a-4f0b-a3d7-2d3dbe2513ab

Screenshot 2024-09-20 125855


After making the changes the server is running but unable login ! ..

**Comment by Anish-bit04** [comment]
hmm, I should have cross checked but the error still remains,
I am new to this project, what should i do to at least run the server.
How are you using it?

**Comment by Adiflickzzz** [comment]
Run it locally.. Facing some issues with docker rn

**Comment by Anish-bit04** [comment]
locally?? you mean without docker

**Comment by Adiflickzzz** [comment]
Yeah! Follow the instructions of installing without docker .. I'll attach tutorial by night ..

**Comment by Anish-bit04** [comment]
Until then whoever want to access only landing page, explore course and notes ,can use it. with docker

**Comment by devsargam** [comment]
Leave it guys. Let's continue with normal approach. Closing this pr for now but will happily accept if u raise again

**Pull request closed without merging**
