### PR TITLE
fix: questions Page, single question page, reply MDeditor

### LINKED ISSUE #935: bug: tags overflowing the container in question section
**Describe the bug**
Tags of the container in Question section overflowing when sidebar is opened

**To Reproduce**
1. Go to app.100xdevs.com
2. Go to the Question section 
3. Open sidebar

**Expected behavior**
Tags shouldn't overflow the container

**Screenshots or GIFs**
Screenshot (177)

**Info (please complete the following information):**
 - Browser: Brave
 - Version: v1.68.141

### LINKED ISSUE #946: bug: Questions section not responsive and improper color contrast for tags
The questions section is not responsive and tags have poor color contrast

image

### PR DESCRIPTION
**Pull request by nischal-shetty2**
### PR Fixes:
- 1 Questions Page
- 2  Single Question Page
- 3 MarkDown editor on reply
- 4  Content and Title fit

https://github.com/user-attachments/assets/4a1be849-1777-4266-9d8b-9a24e143eece

Resolves #946  and Resolves #935
### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by nischal-shetty2** [comment]
@siinghd formatting failing due to this #956 please look into it.

**Comment by nischal-shetty2** [comment]
@hkirat could you look into #956 and also review this

**Comment by siinghd** [comment]
Thank you sir @nischal-shetty2 

/bounty 5$

**Comment by nischal-shetty2** [comment]
glad to help!

**Pull request merged**
