### PR TITLE
fix: overflow issue #167

### PR DESCRIPTION
**Pull request by devsargam**
Fixes: #167

### CODE REVIEW

**Comment by devsargam** [comment]
https://github.com/code100x/cms/assets/76874341/21913884-79a4-4638-9bbc-4163b4d9c669

**Comment by devsargam** [comment]
hey, @hkirat, could u review this?

**Comment by YunusShaikh29** [comment]
hey, @devsargam can you tell me how do I add more video to the website?

**Comment by devsargam** [comment]
@YunusShaikh29 just add dummy video url in video src

**Comment by YunusShaikh29** [comment]
ok let my try, I tried that before but didn't work

**Comment by YunusShaikh29** [comment]
can you connect on X and help me out? @devsargam

**Comment by C0dewithLokesh** [comment]
@hkirat I believe the problem not fixed; I am still unable to scroll through the sidebar independently.

https://www.loom.com/share/6c31db6da3894c058ea7d97b0b7dc203?sid=fc1fce81-8d5e-4416-a56e-4f4f456c4fe5

**Comment by hkirat** [comment]
havent yet deployed the latest

**Pull request merged**
