### PR TITLE
Feat/video search

### PR DESCRIPTION
**Pull request by nimit9**
## Feat: Global Video Search

- Have used **_fuse.js_** library for performing fuzzy search.

[Screencast from 2024-03-27 14-00-03.webm](https://github.com/code100x/cms/assets/37402791/36884766-6490-46c3-9ca2-c6d601c17ba7)

### CODE REVIEW

**Comment by nimit9** [comment]
@hkirat hey, were there merge conflicts?

**Comment by hkirat** [comment]
Lint workflow is failing

**Comment by hkirat** [comment]
ah its because of the merge conflict
will fix it

**Pull request merged**
