### PR TITLE
fix: Enhance Admin UI

### PR DESCRIPTION
**Pull request by abhirajthakur**
Made changes in the Admin UI related to the issue #108 

Dark Theme:
image

Light Theme:
image

### CODE REVIEW

**Comment by hkirat** [comment]
I think a lot of this was already done in https://github.com/code100x/cms/pull/117
Can u get rid of the things that are already there?

**Comment by abhirajthakur** [comment]
> Can u get rid of the things that are already there?

Can you explain it a little bit more? Sorry for inconvenience.

**Comment by hkirat** [comment]
Get rid of the merge conflicts 
Screenshot 2024-03-01 at 10 59 52 AM

**Comment by hkirat** [comment]
Thankyou!

**Pull request merged**
