### PR TITLE
feat: add tooltip on hover of video title (#1550)

### LINKED ISSUE #1550: feature:  Adding hover functionality in SearchBox
A hover feature can be added to the search bar to display the full video title when it doesn’t fit in the box. Currently, longer titles are truncated with ellipses ("..."), but with this improvement, users will be able to hover over the title to see the complete text.

WhatsApp Image 2024-11-07 at 01 55 54_fca9e627

https://github.com/user-attachments/assets/f122b462-700a-4459-b170-befcb51a292c

### PR DESCRIPTION
**Pull request by IkramBagban**
### PR Fixes:
- 1 add tooltip on hover of video title
- 2 working for both the themes (dark, light)

Resolves #1550 

### Checklist before requesting a review
- [✅] I have performed a self-review of my code
- [✅] I assure there is no similar/duplicate pull request regarding same issue

Demo Video

https://github.com/user-attachments/assets/0f6fda9c-1aa0-453a-8098-b6b75e06420a

### CODE REVIEW

**Comment by IkramBagban** [comment]
@devsargam the issue is fixed. please check this

**Comment by devsargam** [comment]
let's use shadcn's tooltip
ref: https://ui.shadcn.com/docs/components/tooltip

**Comment by IkramBagban** [comment]
> let's use shadcn's tooltip ref: [ui.shadcn.com/docs/components/tooltip](https://ui.shadcn.com/docs/components/tooltip)

Sure, please check now

**Comment by Manancode** [comment]
Sir @devsargam I think it would be better to make a custom TooltipWrapper component instead of using a third-party dependency for a simple task. Using dependencies even for small functionality can increase projects overall bundle size. if you approve i can submit another pr with a simple TooltipWrapper component

**Comment by IkramBagban** [comment]
> Sir @devsargam I think it would be better to make a custom TooltipWrapper component instead of using a third-party dependency for a simple task. Using dependencies even for small functionality can increase projects overall bundle size. if you approve i can submit another pr with a simple TooltipWrapper component

I don't think it's a big deal. We're using the ShadCN library for styling across the project. So, if we want to remove this external third-party library, we'll need to replace all ShadCN code with custom styling and components.

**Comment by devsargam** [comment]
@Manancode I think we already use shadcn in a lot of places so most likely it's fine

**Comment by siinghd** [comment]
@IkramBagban  looks fine ty

**Pull request merged**
