### PR TITLE
Fix sidebar scroll issue

### PR DESCRIPTION
**Pull request by C0dewithLokesh**
**Fixes Issue:** #92

**Changes Made:**
- Resolved the issue of Sidebar scroll separation.
- Removed an extra div from the code.

## Demo Video

https://www.loom.com/share/8905bac30dfb4f40ac811bf2729851e8?sid=ad7f0334-cda3-4c07-863e-bbed39a1c960

### CODE REVIEW

**Comment by hkirat** [comment]
This was the right solution
/bounty $50

**Comment by hkirat** [comment]
Closing this but have copied over the changes since need to get it asap and there are conflicts

**Comment by C0dewithLokesh** [comment]
> Closing this but have copied over the changes since need to get it asap and there are conflicts

thanku so much for review and bounty sir

**Comment by C0dewithLokesh** [comment]
> 

@hkirat, It seems now  we're encountering a scrolling issue on the home page. To address this, kindly include `h-full overflow-y-auto no-scrollbar` within the `<main className="max-w-screen-xl flex-col flex text-lg mx-auto pt-10 pb-6>` tag after the recent changes or should i create pull request.

file: `src/app/page.tsx`

I think it's my fault for not checking the code on the homepage sorry about that.

## Issue
image

## After Changes
image

**Comment by hkirat** [comment]
Can u file another PR @C0dewithLokesh ?

**Comment by C0dewithLokesh** [comment]
> Can u file another PR @C0dewithLokesh ?

Done PR: #113

**Pull request closed without merging**
