### PR TITLE
Improved UI for the form in Admin page & added toasts 

### PR DESCRIPTION
**Pull request by pruthviraj7714**
### Checklist before requesting a review
- [✔ ] I have performed a self-review of my code
- [✔] I assure there is no similar/duplicate pull request regarding same issue

**Improved the UI of the Reset Form and added toasts for a better experience.**

Before:
Screenshot (95)

Preview: 
https://github.com/user-attachments/assets/194b6475-4a7f-4e09-9c75-a4de6782f970

### CODE REVIEW

**Comment by siinghd** [comment]
Let me Test it @pruthviraj7714

**Comment by pruthviraj7714** [comment]
@siinghd yeah sure

**Comment by pruthviraj7714** [comment]
@siinghd did you tested?

**Comment by siinghd** [comment]
@pruthviraj7714 ill do it tonight

**Comment by siinghd** [comment]
@pruthviraj7714 i have checked, this, i think the previous ui is looking much better somehow and this one is also missing a feature...
Screenshot 2024-08-08 at 10 33 39 AM
Screenshot 2024-08-08 at 10 34 08 AM

Maybe add the two discord feature in a single line 

and section should be Discord

**Comment by pruthviraj7714** [comment]
@siinghd you mean should I add another account & discord in single section one if front of other?

**Comment by pruthviraj7714** [comment]
@siinghd I raised another PR for this fix please check #865

**Pull request closed without merging**
