### PR TITLE
Fix: Redirect unauthenticated users from /questions,/watch-history to…

### PR DESCRIPTION
**Pull request by maheshsp1809**
**PR Fixes:**
1. Ensured that unauthenticated users are redirected to the sign-in page when attempting to access the `/questions  /questions /watch-history`,  pages.
2. Updated logic to check user session before allowing access to protected routes.

---

**Resolves:**  
#1115

https://www.loom.com/share/11b11e76356b4d6a94f62819f521fa6e
---

**Checklist before requesting a review:**
- [x] I have performed a self-review of my code.
- [ ] I assure there is no similar/duplicate pull request regarding the same issue

### CODE REVIEW

**Comment by maheshsp1809** [comment]
will be closing this as there is already another PR for the same by toufiq

**Comment by toufiqfarhan0** [comment]
maan tell me on this why did you raised a PR I have raised already right?

**Comment by maheshsp1809** [comment]
> maan tell me on this why did you raised a PR I have raised already right?

chill I was just waiting for approval from maintainer  for workflow, so that next time any PR I raise will run that workflow ? dont worry I will be closing it just raised because it was my first.

btw I will close it chill, I have already acknowledged that u have the raised the PR first in your PR.

**Comment by toufiqfarhan0** [comment]
> > maan tell me on this why did you raised a PR I have raised already right?
> 
> chill I was just waiting for approval from maintainer for workflow, so that next time any PR I raise will run that workflow ? dont worry I will be closing it just raised because it was my first.
> 
> btw I will close it chill, I have already acknowledged that u have the raised the PR first in your PR.

OK. My bad! Sorry

**Pull request closed without merging**
