### PR TITLE
feat: add multistage docker build.

### LINKED ISSUE #1368: feat: Multistage Dockerfile
Issue:
- Currently the next-app build image have an enormous size. Adding a multistage docker file to reduce the size of the image.

### PR DESCRIPTION
**Pull request by geekyharsh05**
### PR Fixes:
- Multistage Dockerbuild for reduced image size from `3.06GB` to `213MB`
- Few Dependecies were missing in the package.json.

Resolves #1368 

### All Services Start Correctly
Screenshot 2024-10-02 at 6 44 21 PM

### Dev Mode Logs
Screenshot 2024-10-02 at 6 25 18 PM

### Landing Page
Screenshot 2024-10-02 at 6 47 08 PM

### Logged In Dashboard View
Screenshot 2024-10-02 at 5 55 53 PM

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by geekyharsh05** [comment]
@devsargam

**Comment by TanmayDhobale** [comment]
great

**Comment by devsargam** [comment]
Testing locally

**Comment by devsargam** [comment]
Works like a charm

**Pull request merged**
