### PR TITLE
Added script for adding subtitles to videos that already don't have one

### LINKED ISSUE #875: feature: Write a script that constantly polls the DB and adds subtitles to videos
Screenshot 2024-08-11 at 6 56 42 PM

It needs to get a video without subtitles
Download the video
Transcode it to mp4
convert it to mp3
use Whisper to generate subs
Upload the subs to bunny
Add an entry to `subtitles` fields in the VideoMetadata table

### PR DESCRIPTION
**Pull request by Pritam12F**
### PR Fixes:
- 1 #875 

Resolves #875 

Script that will take contentId of a video, generate and upload the subtitles to bunny in .json format if it doesn't already have subtitles.
It will download the video, convert it to mp3 and generate a .json file in the temp/ folder which I have added to .gitignore and after the subtitle is successfully uploaded, the temp folder/files inside it will be deleted.

Need an OpenAI api key and some other .env variables I have added in the .env.example file

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by siinghd** [comment]
Looks good, let me test it

**Comment by Pritam12F** [comment]
> Looks good, let me test it

Yeah let me know if it works or needs some improvement

**Comment by SujithThirumalaisamy** [comment]
@Pritam12F Can we optimise it? There is a way in ffmpeg to only download the .mp3 from the videoURL.

**Comment by SujithThirumalaisamy** [comment]
And I think our videoJS requires the .srt file for the subtitles. No the JSON format

**Comment by Pritam12F** [comment]
@SujithThirumalaisamy Will fix this

**Comment by SujithThirumalaisamy** [comment]
Tested it locally?

**Comment by Pritam12F** [comment]
> Tested it locally?

I don't have access to an OpenAI api key, so I couldn't test

**Pull request closed without merging**
