### PR TITLE
ui-update

### PR DESCRIPTION
**Pull request by Ashutoshpadhi629**
### PR Fixes:
- 1 responsive UI
- 2 Implemented Most of the Features From Figma File 

Resolves #888 

### Preview-Link : [cms](https://dub.sh/fBqmAjZ)
{username : testuser@example.com , password : 123456} for preview-website

### Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by Ashutoshpadhi629** [comment]
hey @hkirat @siinghd , Although a PR has already been merged, can you review this please ?

**Comment by basedD3v** [comment]
this looks really good. great design, Kudos !

**Comment by Ashutoshpadhi629** [comment]
> this looks really good. great design, Kudos !

Thanks Man

**Comment by siinghd** [comment]
@Ashutoshpadhi629 sirrr too many conflicts

**Comment by siinghd** [comment]
reopen a new PR

**Pull request closed without merging**
