### PR TITLE
Fixed UI-Bugs

### PR DESCRIPTION
**Pull request by keshav-exe**
### PR Fixes:
- 1 FIxed UI bugs
- 2 Improved Video Chapters
- 3 Fixed Readme
- 4 Added keyboard shortcut to access search
- 5 Added global search within course (referred @ItsFlash10's code)
- 6 Added dynamic metadata to courses

Resolves Almost all the ui related issues

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

Before

https://github.com/user-attachments/assets/17de2416-2acf-4fc9-b05a-f2f4df1887f5

After

https://github.com/user-attachments/assets/c6ff0eb9-f579-4f87-bd84-f0e602dd4d31

### CODE REVIEW

**Comment by keshav-exe** [comment]
@devsargam @hkirat please have a look at this. Fixes a lot (almost all) of the ui related bugs/issues...

**Comment by amanbairagi30** [comment]
sir is this the expected behaviour ? i guess it is supposed to slightly more width than this ?

https://github.com/user-attachments/assets/d26b3cd0-29be-465c-b51e-942cf09d326c

**Comment by keshav-exe** [comment]
Hey @amanbairagi30, thanks for pointing that out! That page was in a previous PR, will fix it now.

**Comment by devsargam** [comment]
Added to things to review :)

**Comment by ItsFlash10** [comment]
@keshav-exe #1176 also has search API changes, you can either bring it here or we can get it merged separately. Works both ways.

PS: Let it get merged separately [Want the increased contribution count lol]xD

cc: @devsargam

**Comment by siinghd** [comment]
@keshav-exe Bhai next try to split changes in different PR's as its much easier to go through and if something happens we can roll back quickly for each functionality and not whole PR

**Comment by siinghd** [comment]
@keshav-exe also if you can provide before/after video

**Comment by siinghd** [comment]
@keshav-exe Sir, please provide before after video otherwise will close the PR in five days/

**Comment by keshav-exe** [comment]
@siinghd sorry I just saw this, will doing before and after right away!

**Comment by keshav-exe** [comment]
> @keshav-exe Bhai next try to split changes in different PR's as its much easier to go through and if something happens we can roll back quickly for each functionality and not whole PR

noted bhai🫡

**Comment by devsargam** [comment]
Hey @keshav-exe, can you make more atomic small changes in a pr. Also there are merge conflicts here. Closing for now. Feel free to open small but many

**Pull request closed without merging**
