### PR TITLE
added change password feature

### PR DESCRIPTION
**Pull request by AuenKr**
### PR Fixes:
- Added change password directly from `app.100xdevs.com` while maintaining password synchronization with `harkirat.classx.co.in`

Assumption env variable
APPX_AUTH_KEY = appxapi
APPX_CLIENT_SERVICE = Appx

UI `/password`
change Password Page

### Resolves
- #748 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by atul24112001** [comment]
Hey, I have created the same pr But it got closed by maintainers. https://github.com/code100x/cms/pull/1415

**Comment by AuenKr** [comment]
@devsargam ,
Earlier I also created PR for the same feature #749 .
That was not matching the current UI, so created a new one that does not have conflicts.

**Comment by devsargam** [comment]
@hkirat thoughts on this? else closing this pr within a week

**Comment by AuenKr** [comment]
@devsargam @hkirat, I just want to know why it was closed previously.

previous reason:
1. The password is not in sync with appx.
2. Appx does not expose any endpoint for that.

as both reasons are resolved, is there any other reason for not changing the password directly from cms instead of using the appx site?

**Comment by devsargam** [comment]
This probably is not available from server side if I am not wrong but I will get to kirat regarding it

**Pull request closed without merging**
