### PR TITLE
Resolved signin on pressing enter #123 and changed NEXT_PUBLIC_BASE_URL_LOCAL url

### LINKED ISSUE #123: Pressing enter on the signin page should sign the user in
After filling login credentials, the submit button has to be separated clicked on or tabbed on to. The form does not submit just by pressing ENTER key after filling in the password

### PR DESCRIPTION
**Pull request by Maawan**
Resolved #123 and #124

### CODE REVIEW

**Comment by devsargam** [comment]
@Maawan 
There are things called hooks in git which run when certain actions in git. If you know react it's like useEffect whenever you change a state variable it makes a side effect
Here, a tool called `husky` is used which adds all the files when you commit.

**Comment by Maawan** [comment]
@devsargam Thanks dude. I'm closing this request and will again try to contribute after understanding this husky thing :)

**Comment by devsargam** [comment]
Alright @Maawan GL

**Comment by Maawan** [comment]
Sorry to again disturb you @devsargam , I understood about husky and found out the reason why my package-lock and yark.lock is getting committed automatically due to husky precommit rule. But I have another issue, I am just using npm install and its changing my package-lock and yarn.lock. So, whenever I am working in some file like in this request I changed some code in Signin.tsx and .env.example, when I am commiting it, due to husky precommit rule, my all files are getting commited so I am confused that whether it is ok to do a pull request with some unneccessary file changes which is done due npm install on my local system and if not than how could I avoid this issue. I will be glad if you answer to this question :)

**Comment by devsargam** [comment]
@Maawan it is not advised to open a pr with unwanted files since that's just an overhead for maintainer kirat in this case.
You can either remove the changes from yarn.lock manually or skip the git hooks completely with --no-verify flag in git commit. This is not suggested everywhere but  could be used in this case.
```
git commit -m 'your commit message' --no-verify
```
This will not run git hooks | husky

**Comment by Maawan** [comment]
@devsargam Thanks dude for the help

**Pull request closed without merging**
