### PR TITLE
fix: auth check in payout-methods and navbar overflow in payout-methods as well as calendar.

### LINKED ISSUE #1201: bug: Payout Methods is UNPROTECTED from Authentication Check and along with Calendar their Navbars are Overflowing onto the Page Contents as well.
**Describe The Bugs**
1. The /payout-methods route is unprotected from authentication check i.e, users can access this page irrespective of them being logged in or not.
2. The /payout-methods and /calendar pages have their Navbar overflowing onto the page contents which leads to it not being visible completely.

**To Reproduce**
**Steps to reproduce the behavior of Issue 1:**
1. Visit https://app.100xdevs.com/payout-methods using any browser window that does not have your logged-in cookie (ex. incognito)
2. You will still be able to access this page even if you aren't logged in.

**Steps to reproduce the behavior of Issue 2:**
1. Visit /payout-methods and /calendar routes at app.100xdevs.com.
2. You will notice the Navbar overflows onto the contents of the page. 

**Expected behavior for Issue 1**
Users who are logged in should only be the ones allowed to access the page. (i.e only who has the auth cookie)

**Expected behavior for Issue 2**
The Page Contents should follow under the Navbar with appropriate padding and margin.

**Video for Issue 1**

https://github.com/user-attachments/assets/e031e387-2f01-4839-ba44-47508e309e6b

**Video for Issue 1**

https://github.com/user-attachments/assets/2ab0671f-8389-4cac-9b62-3f28ed16322f

**Info (please complete the following information):**

**Additional context**
#1159 and #1168 already dicusses about the Navbar overlow issue but donot completey fix the authentication bug as well.

### PR DESCRIPTION
**Pull request by rahulbarmann**
### PR Fixes:
- Issue 1: Auth check is performed on /payout-methods and only logged-in users are allowed to access this page
- Issue 2: Both /calender and /payout-methods page contents are under the Navbar with proper margin and padding. 

Resolves #1201

**Before:**[ (In Greater Detail)](https://github.com/code100x/cms/issues/1201)

**After:**

**Solution Video For Issue 1:**

https://github.com/user-attachments/assets/03986005-c1c4-4811-b386-c232fcabfeea

**Solution Video For Issue 2:**

https://github.com/user-attachments/assets/973c5767-45b4-4fbc-be9b-0073b8c74cc9

### Checklist before requesting a review
- ☑️ I have performed a self-review of my code
- ☑️ I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by rahulbarmann** [comment]
### Additional Improvement Discussion

The commit I pushed in this PR moved `/payout-methods` and `/calendar` into the `(main)/(pages)/` directory. I did not change any file contents except some import paths in `/payout-methods` as shown below:

image

I would suggest to remove the unnecessary auth-check present in the calendar route separately, as now all of the auth-checking is already performed by the `layout.tsx` in the `(pages)` directory:

Screenshot from 2024-09-13 03-08-02

But now the `/calendar` still has an unnecessary auth check as shown below:

Screenshot from 2024-09-13 03-15-45
 
### My Proposal

I propose to remove the second unnecessary auth-check in `/calendar`, I have already tried and tested it locally and it works fine. It would be great if I was allowed to add this change as well. Otherwise, the original PR anyways solves the issue #1201.

**Comment by siinghd** [comment]
@rahulbarmann Bhai its empty PR

**Comment by rahulbarmann** [comment]
@siinghd Sorry but may I know what you mean by empty PR? I did commit the changes in this PR but the changes are very minimal (only folder location change and import paths) to fix the issue:

Screenshot from 2024-09-16 14-24-13

On top of this, I additionally requested permission to delete the unnecessary auth-check in `/calendar` in the "Additional Improvements" section of the PR comments.

**Comment by devsargam** [comment]
There's nothing changed here. @rahulbarmann can u double check again and raise another pr? Closing as of now

**Pull request closed without merging**
