### PR TITLE
Feature: Integrate Code Quality Tools for Enhanced Consistency

### PR DESCRIPTION
**Pull request by TanmayDhobale**
This pull request introduces ESLint, Prettier, and Husky into our development workflow. The integration of these tools serves to enforce a consistent coding standard across the project, ensuring that all contributions adhere to our defined styles and practices. 

Key Changes:
- ESLint: Setup to analyze the codebase for adherence to our coding standards, helping identify potential errors and code smells.
- Prettier: Configured to automatically format code according to our specified styles, ensuring consistency in the appearance and structure of our code.
- Husky: Employed to trigger ESLint and Prettier checks before committing changes, ensuring that only code that meets our quality standards is added to the repository.

These tools collectively contribute to a more maintainable and error-free codebase, streamlining the development process and enhancing collaboration efficiency.

### CODE REVIEW

**Comment by TanmayDhobale** [comment]
@hkirat  this is right approach  ?

**Comment by devsargam** [comment]
I might be wrong but we do alreay have husky, eslint and prettier

**Comment by TanmayDhobale** [comment]
@devsargam We've updated and fine-tuned our existing Husky, ESLint, and Prettier configurations to enhance code consistency and automation further

**Comment by adexh** [comment]
With so many files touched, its difficult to review the changes which are done particularly for this PR.

**Comment by TanmayDhobale** [comment]
@adexh  This PR mainly updates our ESLint, Prettier, and Husky setups. Most changes are automatic formatting, so please focus on the config updates

**Comment by devsargam** [comment]
Linting can be a separate pr actually

**Comment by TanmayDhobale** [comment]
@devsargam  umm ???

**Comment by devsargam** [comment]
I mean a lot of files have been changed which makes ur pr hard to review. Can u revert all the linted files and only focus on what was changed actually?

**Comment by TanmayDhobale** [comment]
Most changes are automatic formatting  !!!!

**Comment by TanmayDhobale** [comment]
lets see I'll revert the formatting changes in the linted files to highlight the key updates made to our ESLint, Prettier, and Husky configurations, ensure the PR focuses only on the essential modifications. good ?

**Comment by hkirat** [comment]
@devsargam is right, need to be saparate changes
Wholesale lint will probably happen when PRs are at 0 so that people don't have merge conflicts
Can you PR just the eslint changes and remove the automatically generated code?

**Comment by TanmayDhobale** [comment]
> @devsargam is right, need to be saparate changes Wholesale lint will probably happen when PRs are at 0 so that people don't have merge conflicts Can you PR just the eslint changes and remove the automatically generated code?

okk

**Pull request closed without merging**
