### PR TITLE
feat: users can now see their watch history

### LINKED ISSUE #250: Add new History feature
Requesting a feature similar to YouTube's history tracking in Code100x. 
This would enhance user experience by allowing them to easily resume their coding journey and revisit previously viewed videos.

Something like this -

Screenshot from 2024-03-20 13-20-38

### PR DESCRIPTION
**Pull request by nimit9**
### Closes #250 : Watch History
- Users can now see their watch history

### Uploaded video after changing the code on 24/3/2024: 
[Screencast from 2024-03-24 19-47-20_compressed.webm](https://github.com/code100x/cms/assets/37402791/92a13ae0-d037-4a56-a54b-9250d065ae38)

### Added previous year date
Screenshot from 2024-03-24 20-17-09

### PS
- Added extra videos to test in local db using seed.ts file. Code for that -> https://gist.github.com/nimit9/b8a06963add1f8e8aef4750e2a7777a0

- Used [Carousel](https://ui.shadcn.com/docs/components/carousel) from shadcn which uses [Embla-Carousel](https://www.embla-carousel.com/) library, hence the added dependency in package.json

- @hkirat will resolve the Merge Conflicts that might come up once #245 is merged.

### CODE REVIEW

**Comment by nimit9** [comment]
@hkirat could you please review this whenever you get the time

**Comment by nimit9** [comment]
@hkirat could you please review this and the other PR (feat/bookmarks)

**Comment by nimit9** [comment]
WIll you be reviewing this as well today? @hkirat 
Will resolve the conflicts once #281 is merged, as it might create more conflicts

**Comment by hkirat** [comment]
Great feature, lots of merge conflicts tho (my bad)
Mind cleaning them?

**Comment by nimit9** [comment]
Hey @hkirat, fixed the conflicts

**Pull request merged**
