### PR TITLE
added change password feature

### PR DESCRIPTION
**Pull request by AuenKr**
### PR Fixes:
- #748

### Description
user can change their password now
For both [cms](https://app.100xdevs.com/) && [100xdev](https://100xdevs.com/) simultaneously

### Result

https://github.com/code100x/cms/assets/103646877/7478248f-223d-40fe-8b38-aa899364263d

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by AuenKr** [comment]
@hkirat check this out

**Comment by AuenKr** [comment]
> we cant do this yet, passwords are synced from https://harkirat.classx.co.in

the password u change from `https://app.100xdevs.com/` will also be updated in `https://harkirat.classx.co.in`
This way they both are synced with each other

**Comment by AuenKr** [comment]
@hkirat ??

**Comment by hkirat** [comment]
appx doesnt expose the endpoint to change password unfortunately

**Comment by AuenKr** [comment]
> appx doesnt expose the endpoint to change password unfortunately

This is endpoint for appx to change password (found from network tab while changing my password)
And password in synced with both the sites as explain previously.

```
/Post  https://harkiratapi.classx.co.in/post/changesecurity

headers: {
    "auth-key" : "appxapi",    // APPX_AUTH_KEY env variable
    "authorization" : "User JWT token "
}
FormData : {
    "currentpassword" : "User current password",
    "newpassword" : "New password",
    "confirmpassword" : "New Password",
    "userid" : "User appx id"   
}
```

Appx endpoint

**Comment by AuenKr** [comment]
@hkirat I have use above mention endpoint of appx to change user password.
We can use it in that way right??
Any other feedback??

**Pull request closed without merging**
