### PR TITLE
feat: Enhance the Admin UI

### PR DESCRIPTION
**Pull request by devsargam**
# Changes in this PR:
- [x] Have consistent behaviour in dark/light mode in admin
- [x] JSON segments can now be validated in UI itself
- [x] Replace all `input` with `Input` from shadcn/ui
- [x] Replace all `button` with `Button` from shadcn/ui

# UI before the PR:
https://github.com/code100x/cms/assets/76874341/b2bfe880-5848-4f5f-b651-fba2cbd36a2a

# UI after the PR:
https://github.com/code100x/cms/assets/76874341/d58688ef-90b2-4a84-90b4-b48fcbd5c1f1

### CODE REVIEW

**Comment by devsargam** [comment]
hey @hkirat, could you please review this?
It has no functional changes but only UI so you need not worry

**Comment by hkirat** [comment]
Will check in a few
sorry got deprioritised since its admin only

**Comment by devsargam** [comment]
Hii, implemented the following here to save your time:

Admin to create course: http://206.189.130.144/admin
Toggle DRM & add metadata: http://206.189.130.144/admin/userflags
Admin for content: http://206.189.130.144/admin/content/1
Admin for discord stuff: http://206.189.130.144/admin/discord

#### AdminPassword ="ADMIN_SECRET"
#### userPassword="123456"

**Comment by devsargam** [comment]
Thanks kirat🙇🏻‍♀️

**Pull request merged**
