### PR TITLE
feat: connect the questions to the video

### LINKED ISSUE #862: feature: Connect the question to the video (High priority - valuable bounty)
We already have a platform for questions at [100xdevs](https://app.100xdevs.com/questions), but it is currently underutilized.

To increase engagement, I propose connecting questions to specific videos. Here's a plan for implementation, which can be further improved for a better outcome:

### Proposed Features:

1. **Linking Questions to Videos**:
    - When creating a question, users should have the option to link it to a specific video.
    - Users can either search for a video or select one from a searchable dropdown menu. 
    - This feature should be optional, as we still want to allow questions without associated videos.

2. **Video Integration**:
    - Each video should have a button that, when clicked, redirects the user to all questions related to that video.

3. **Database Changes**:
    - Add an optional `video_id` field to the question table to store the associated video ID.

4. **Future Improvements (V2)**:
    - Implement notifications to a specific Discord channel when a new question is created.

---

Note: These are initial thoughts, and any further improvements are welcome! (do not limit to only initial thoughts!)

### PR DESCRIPTION
**Pull request by ezhil56x**
### PR Fixes: #862 
Covered all the features proposed in the issue

#### Linking Questions to Videos
- While creating a new question users can link a lecture video to it
- Users can either search for a video or select one from a searchable dropdown menu
- This feature should be optional, as we still want to allow questions without associated videos.
- Users can view all questions related to a particular lecture video

#### Video Integration
- Each video should have a button that, when clicked, redirects the user to all questions related to that video.

#### Database Changes
- Add an optional video_id field to the question table to store the associated video ID.

https://github.com/user-attachments/assets/86248d72-8964-4a7c-8eb8-f2a201b846ce

Resolves #862 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by siinghd** [comment]
@ezhil56x looks really good, lets just add two things

one minute 1:03 when i click on ask question button it open the modal thats really good!
lets add another query parameter, &fromvideo=videoid... this way when the modal opens the video is already there and the user doesnt have to search

Second: the questions page lets add the possibility to filter questions based on a specific video... maybe add a same search dropdown and when user selects the video only that questions appear 

/bounty 25$

**Comment by siinghd** [comment]
also fix merge conflicts

**Comment by ezhil56x** [comment]
@siinghd Updated my PR with the requested changes

https://github.com/user-attachments/assets/2251c4d4-16da-48d9-9dda-046a7296acb7

**Comment by devsargam** [comment]
@siinghd for rereview

**Comment by ezhil56x** [comment]
Resolved conflicts. Hoping it to get merged at the earliest to avoid further conflicts.

**Comment by avparadox** [comment]
@devsargam i know i shouldn't tag a maintainer this way. But it's a request, could you please ask Singh Bro to review this PR. 

PR looks amazing & I felt bad that it is being stalled for 2 weeks. I might not be able to make such PR, but the guy did so, so sir if could please look into it. It would be great.

Thanks.

**Comment by devsargam** [comment]
@avparadox thinking of removing the questions endpoint totally since it is causing many conflicts are not a lot of people are using it a lot

**Comment by avparadox** [comment]
Maybe we can ask Kirat bro if  he wish to take a Quick QnA before every class. If he agrees to it, then maybe PR makes a sense or else I believe it is good to be removed.

**Comment by devsargam** [comment]
I asked him and he agreed it could be removed but I really like the idea of reading questions present in the QnA area

**Comment by avparadox** [comment]
Even I liked the QnA page. If people interact, a lot of good content can be seeded like Stackoverflow. But as a dev, we can't control the engagement things. Probably you can declare this as closed. 

The guy who made this PR, I salute him 🫡.
He have done justice to the issue. I probably can't make such a good PR right now. He has done a commendable job 🙌🏻

Thanke @ezhil56x 👏🏻

**Comment by devsargam** [comment]
@avparadox I agree.
@ezhil56x can you give me your upi address I will at least transfer some amount for the effort. Sorry but I can't merge this right now but this is great.

**Pull request closed without merging**
