### PR TITLE
 Resolve overlap issue of the last sidebar element with the footer menu across all devices

### PR DESCRIPTION
**Pull request by rajveeerr**
### PR Fixes:  
- Last sidebar element being overlapped by the footer menu on all devices (mobile, tablet, laptop)
- Improved sidebar responsiveness for large screen sizes

**Issue Description:**
1. The last element of the sidebar was always overlapped by the footer menu, causing usability issues. This problem occurred consistently across all screen sizes.
2. Navigation was not optimally responsive for 13-inch laptop screens.

**Fix Description:**
1. Applied a padding-bottom of `6rem` to the sidebar to ensure sufficient space for the last element to be visible above the footer menu.
2. Updated Tailwind responsive classes from `2xl` to `lg` in AppBar component
3. Increased the AppBar width from 12vw to 20vw to accommodate all navigation items on smaller screens
4. Implemented a more consistent navigation experience across different device sizes

### Checklist before requesting a review:
- [x] I have performed a self-review of my code
- [x] Addressed mentor's feedback on navigation responsiveness
- [x] Ensured no similar/duplicate pull request exists
- [x] Tested across multiple device sizes

### Screenshots of the overlaping Issue (Mobile)  

| **Before (Issue)**                        | **After (Fixed)**                         |  
|-------------------------------------------|-------------------------------------------|  
| Mobile Before | Mobile After |  

### Screenshots of changes sidebar layout(1024px - Laptop Screen Width)

| **Before (Old Implementation)** | **New Implementation (Sidebar Closed)** | **New Implementation (Sidebar Open)** |
|---------------------------------|------------------------------------------|---------------------------------------|
| Before Screenshot | Sidebar Open Screenshot | Sidebar Closed Screenshot |

**Observations at 1024px:**
- Sidebar now fully visible and functional
- All menu items accessible
- Consistent layout with larger screen designs

### Additional Notes
- Week 17 (previously cut-off last item) is now fully visible on mobile devices
- Navigation is now responsive and consistent across different screen sizes
- Bottom padding ensures no content is hidden by footer menu

@hkirat @siinghd @devsargam

### CODE REVIEW

**Comment by rajveeerr** [comment]
@devsargam @siinghd

**Comment by devsargam** [comment]
hey if possible can you make the footer menu also like side nav on 13inch laptops?

**Comment by devsargam** [comment]
going to sleep will review later

**Comment by rajveeerr** [comment]
> hey if possible can you make the footer menu also like side nav on 13inch laptops?

Sure, I can give it a shot!

**Comment by rajveeerr** [comment]
> hey if possible can you make the footer menu also like side nav on 13inch laptops?

I've addressed your feedback with the additional changes:
- I've implemented the requested modification to make the footer menu behave like a side navigation for 13-inch laptops. 
- Updated Tailwind responsive classes from `2xl` to `lg`in AppBar component
- Increased the width of AppBar to incorporate all the items for smaller screens(earlier it was 12vw, changed it to 20vw)

Changes are now pushed to the branch. Please review at your convenience.

**Comment by rajveeerr** [comment]
@devsargam can you please review these changes?

**Comment by devsargam** [comment]
Thank you sir

**Pull request merged**
