### PR TITLE
cleaned up the App-Bar- and as per kirats request removed the pnpm-lock file 

### PR DESCRIPTION
**Pull request by RahulMishra0722**
### PR Fixes:
- 1. Cleaned-Up The App-Bar 
Screenshot 2024-04-17 at 4 07 01 AM
This is What it looks like when hovering
Screenshot 2024-04-17 at 4 30 34 AM
When not hovering
Screenshot 2024-04-17 at 4 31 23 AM

Resolves #[Issue Number if there] 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by nimit9** [comment]
Already fixed in #319

**Comment by RahulMishra0722** [comment]
Here is the ss from last pr for context Screenshot_2024-04-17-05-19-53-81_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by RahulMishra0722** [comment]
did not added discord logo closing this

**Comment by RahulMishra0722** [comment]
did not added discord logo closing this

**Pull request closed without merging**
