### PR TITLE
Fix Question and Answer UI

### LINKED ISSUE #1046: The Question Page UI is broken.
The UI of the Questions and Answers Page is broken. It's totally unreadable.

### Questions List
Old Question 1

### Question Page
Old Question 2

### Answers
Old Answers 3

I have already worked on this and will make a PR soon.

### PR DESCRIPTION
**Pull request by zenithexe**
### PR Fixes: 
- 1 Improves the UI of the Questions List
- 2 Implements new UI for Answers

Resolves #1046 

### Questions List
New UI 1

### Question Page
New UI 2

### Answers List
New UI 3

Video :
https://github.com/user-attachments/assets/33db7a36-f890-4031-8fb1-c35a95cc1088

### Few Things to mention :
- Previously we have been using a single `PostCard` Component for rendering both Questions as well as Answers. I am created two new components `QuestionPost` and `AnswerPost` to render them differently.
- Also, for some reason (which I am unaware of) we are using both Pages Router and App Router of Nextjs in the codebase. However, I  implemented the components in both the routing `pages.tsx` files.

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by zenithexe** [comment]
@hkirat @devsargam , if you guys can have a look at this PR. I hope you like the UI.

( This PR was having a merge conflict, which I resolved. The linting issue keeps happening due to some extra brackets for the regex in `src/actions/payoutMethods/schema.ts`. )

**Comment by palveVaishnav** [comment]
great one, your comment answer section looks cool.
Are you still working on it ? 
Can I improvise it a bit in my PR #1123  ?

**Comment by devsargam** [comment]
You should not have `yarn.lock` or `package-lock.json`

**Comment by zenithexe** [comment]
@devsargam , Let me fix the issue and make a new PR. Do you approve the new UI design ?

**Comment by zenithexe** [comment]
@devsargam I have made a new PR #1124

**Pull request closed without merging**
