### PR TITLE
Fix/folder structure

### PR DESCRIPTION
**Pull request by atul24112001**
### PR Fixes:
- Folder Structure
- Type & NextJs errors
- Content UI
- Deleted unused files

Resolves #[Issue Number if there] 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

Screenshot 2024-09-27 at 3 26 33 PM

### CODE REVIEW

**Comment by atul24112001** [comment]
The reason for this ui change is youtube or udemy  has similar layout for content & the navigation liks at the bottom of the screen doesn't look good in big screens that's why moved those to navbar, but Its same as before for small devices.

**Comment by atul24112001** [comment]
@devsargam

**Comment by devsargam** [comment]
This pr is almost impossible to merge sir

**Comment by devsargam** [comment]
I know you did a great job but it will open like infinite conflicts

**Comment by atul24112001** [comment]
Ok No problem, But It will create conflicts in other PRs or something else ??

**Comment by devsargam** [comment]
image

**Pull request closed without merging**
