### PR TITLE
Feat: added chapters like YT on video's right

### PR DESCRIPTION
**Pull request by nimit9**
Hey  @hkirat, Is this the desired functionality? Let me know if I need to change something.
The cursor didn't show up in the recording, the video is seeking to the start time of the segment on clicking the chapter 

[Screencast from 2024-02-01 21-32-47_compressed.webm](https://github.com/code100x/cms/assets/37402791/46810b27-0b9e-422b-b449-7e9b8b87cb09)

### CODE REVIEW

**Comment by hkirat** [comment]
Should be toggleable so user can close it

**Comment by nimit9** [comment]
> Should be toggleable so user can close it

Will add that

**Comment by nimit9** [comment]
Hey @hkirat, made it toggleable

[Screencast from 2024-02-02 03-27-04.webm](https://github.com/code100x/cms/assets/37402791/3e3c1c4c-7d40-45a6-9cc7-991c09e4b6f1)

**Comment by hkirat** [comment]
/bounty $10 . Some follow ups here - https://github.com/code100x/cms/commit/4c01cb2c958071211bf3d878b53cbba1856c0e2e

**Comment by nimit9** [comment]
> /bounty $10 . Some follow ups here - https://github.com/code100x/cms/commit/4c01cb2c958071211bf3d878b53cbba1856c0e2e

Thanks! 
Forgot to check some rookie mistakes, and edge cases

**Pull request merged**
